### PR TITLE
fix outbound config reload

### PR DESCRIPTION
**Pull request by celesteking**
Some smartass decided to split outbound into pieces and forgot to code the config reload properly.

Checklist:
- [ ] docs updated
- [x] tests updated
- [x] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

### CODE REVIEW

**Comment by celesteking** [comment]
Strangely, no one noticed this before. And I spent several hours to understand why outbound delivery suspension didn't work.

**Comment by msimerson** [comment]
In principle, I agree with this change. Changing `cfg` to something else makes sense, because everywhere else in Haraka we use `cfg` to represent the parsed configuration. What I don't like is the name `cfgmod`. It's  too generic. Is it a modified config? A config module? Is it  **the** `haraka-config` module?

What it is is the *parsed outbound config*. That's a mouthful. So how about naming the variable obcfg, or ob_cfg?

**Comment by celesteking** [comment]
You can't agree or disagree in this case as this is essentially a bugreport ;)

**Comment by msimerson** [comment]
> Shall I do the needful?

Yes please. And then I will too.

**Comment by celesteking** [comment]
Update: actually, I object ob_cfg as we'll have to use ob_cfg.cfg which doesn't look nice.

**Comment by msimerson** [comment]
I agree, redundancy isn't a good look. Proposal: `const ob_cfg = require('./config').cfg;`

**Comment by celesteking** [comment]
... have you seen the patch? We can't use that as cfg object is being reassigned on config reload. That was the whole point/issue.

**Comment by msimerson** [comment]
Okay, `const obc = require('./config');` and then reference it with `obc.cfg`?

**Comment by celesteking** [comment]
here you go

**Pull request merged**
