### PR TITLE
P42: inline variables

### PR DESCRIPTION
**Pull request by unquietwiki**
P42.ai: ESLint inlining of variables

### CODE REVIEW

**Comment by unquietwiki** [comment]
@msimerson Hey, I saw you just posted a new branch while I was submitting this one. I ran the inline stuff & ESlint to clean up the whitespace per project rules.

**Comment by msimerson** [comment]
Yeah, I'll stop now, so we aren't colliding. Go ahead and have your fun. :-)  (Hint though: much faster to run `npm run lint` locally and `npm test` than to wait for it to fail during the CI tests.

**Comment by unquietwiki** [comment]
> Yeah, I'll stop now, so we aren't colliding. Go ahead and have your fun. :-) (Hint though: much faster to run `npm run lint` locally and `npm test` than to wait for it to fail during the CI tests.

Thanks man. I won't be able to do too much more tonight, so I'll fix that remaining error in this & maybe one or two more things.

**Comment by msimerson** [comment]
If you haven't discovered it already, there's a `npm run lintfix` target that will auto-fix all the lint problems for you.

**Comment by unquietwiki** [comment]
> 

Yeah, I was using --fix; the issue here was having to re-run the inline process. Pushing that now; had to put kiddo to bed!

**Comment by unquietwiki** [comment]
@msimerson I'm gonna abandon this PR & recreate based on the recent merges.

**Pull request closed without merging**
