### PR TITLE
add auth support to smtp_forward

### PR DESCRIPTION
**Pull request by msimerson**
I think we should merge this and close #430 

Thoughts?

closes #430

### CODE REVIEW

**Comment by Dexus** [comment]
if we merge it, we need also docs updated.
But from me its ok.

**Comment by baudehlo** [comment]
What are the hard-coded base64 values in there?

**Comment by smfreegard** [comment]
@baudehlo:   Username: and Password:   It's for AUTH LOGIN that prompts for each that way with 3xx responses.

**Comment by smfreegard** [comment]
What about auth_proxy?  That was what #430 did.

**Comment by msimerson** [comment]
PR can't be merged as-is, so if that feature is still desired, and someone takes it upon themselves to fix it up, they'll have to open a new PR anyway. So might as well close it, eh?

**Comment by smfreegard** [comment]
(thumbs-up)

**Pull request closed without merging**
