### PR TITLE
Use utf8 encoding now for QP not binary

### PR DESCRIPTION
**Pull request by baudehlo**
Replaces #1418 .

### CODE REVIEW

**Comment by baudehlo** [comment]
Tests are failing because spameatingmonkey appears to be down.

**Comment by baudehlo** [comment]
Better fix for #1417

**Comment by DarkSorrow** [comment]
Yes this work on the mail i've sent with the encoding, i will try to make some more test later too.
I closed my other request.

**Comment by baudehlo** [comment]
Merged

**Pull request merged**
