### PR TITLE
Attempt to fix outbound shutdown error

### LINKED ISSUE #1570: Socket in pool got FIN
@baudehlo Removing the line configuration of  `pool_timeout=0`, in the latest version from master, just like the default config is I am getting this error.

"fin" in spanish means end, but I am not sure if that means the same in SMTP context :smile: 

image

### PR DESCRIPTION
**Pull request by baudehlo**
This is just a belt and braces attempt to stop Haraka shutting down from the error @ricardopolo reported here: https://github.com/haraka/Haraka/issues/1570

If it works: Fixes #1570

### CODE REVIEW

**Comment by ricardopolo** [comment]
In my testing it works :+1: :shipit:

**Comment by ricardopolo** [comment]
I have some bad news... after more intensive testing I am seeing this exception.

I think the PR did something, the old error does not appear. But we have this new one
image

**Comment by baudehlo** [comment]
Right, but does the server shut down after that?

**Comment by ricardopolo** [comment]
Not @baudehlo the server did not shutdown, just show the error but continues working

**Comment by baudehlo** [comment]
Yes that's expected.

**Comment by ricardopolo** [comment]
Nice. But if this is a expected behavior I would change the log from Warn to Info. 

I dont think is nice to have lots of warns in the logs when are normal operations behaviors.

**Comment by baudehlo** [comment]
Well it's a warning because the remote end really isn't supposed to do that. It's not very nice of them. But I can lower it to NOTICE perhaps.

**Comment by baudehlo** [comment]
Following discussion on IRC, I've lowered the default timeout to 50s. It seems most servers have a longer timeout than that, so this should eliminate this warning.

**Comment by ricardopolo** [comment]
Sadly the issue continues, I configure pool_timeout to 30 and we sill have this error.


screen shot 2016-09-22 at 2 56 02 pm

So would you change the log level please?
Thanks!

**Pull request merged**
