### PR TITLE
haraka.service: Type=simple

### PR DESCRIPTION
**Pull request by tomscytale**
`systemctl start hakara.service` was hanging, but the service was started ok. This is because the process wasn't forking and does not appear to have an option to do so. 

https://superuser.com/a/1274913/117296

> a) If the service starts and keeps running, and the prompt does not return until you press Control-C or stop the service in some other way: then Type = simple is the right choice.
> b) If the prompt returns but the service keeps running in the background (i.e. the service daemonizes itself on its own), then Type = forking is the right choice.

Fixes #

Changes proposed in this pull request: none 

Checklist:
- [ ] docs updated
- [ ] tests updated
- [ ] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

### CODE REVIEW

**Comment by tomscytale** [comment]
seems fine - with `nodes=2`:

```
sudo journalctl -xe
...
Mar 15 18:34:00 kollaps-music haraka[14259]: Starting up Haraka version 2.8.23
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugins
Mar 15 18:34:00 kollaps-music haraka[14259]: log format: DEFAULT
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugin: dnsbl
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugin: helo.checks
Mar 15 18:34:00 kollaps-music haraka[14259]: Starting up Haraka version 2.8.23
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugins
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugin: mail_from.is_resolvable
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugin: rcpt_to.in_host_list
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugin: dnsbl
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugin: data.headers
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugin: helo.checks
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugin: queue/smtp_forward
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugin: mail_from.is_resolvable
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugin: max_unrecognized_commands
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugin: rcpt_to.in_host_list
Mar 15 18:34:00 kollaps-music haraka[14259]: [NOTICE] [-] [max_unrecognized_commands] the plugin max_unrecognized_commands has been replaced by 'limit'. Please update c
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugin: data.headers
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugin: queue/smtp_forward
Mar 15 18:34:00 kollaps-music haraka[14259]: [INFO] [-] [core] Loading plugin: max_unrecognized_commands
Mar 15 18:34:00 kollaps-music haraka[14259]: [NOTICE] [-] [max_unrecognized_commands] the plugin max_unrecognized_commands has been replaced by 'limit'. Please update c
Mar 15 18:34:00 kollaps-music haraka[14259]: [NOTICE] [-] [core] Listening on :::25
Mar 15 18:34:00 kollaps-music haraka[14259]: [NOTICE] [-] [core] worker 1 listening on ::0:25
Mar 15 18:34:00 kollaps-music haraka[14259]: [NOTICE] [-] [core] Listening on :::25
Mar 15 18:34:00 kollaps-music haraka[14259]: [NOTICE] [-] [core] worker 2 listening on ::0:25
```

```
tom@host:~$ ps alx 
F   UID   PID  PPID PRI  NI    VSZ   RSS WCHAN  STAT TTY        TIME COMMAND
...
4     0 14259     1  20   0 1004460 39648 -     Ssl  ?          0:00 node /home/haraka/bin2/haraka -c /home/haraka/haraka
0     0 14320 14259  20   0 897128 39028 -      Sl   ?          0:00 /usr/bin/node /home/haraka/node_modules/Haraka/haraka.js -c /home/haraka/haraka
0     0 14321 14259  20   0 897000 38908 -      Sl   ?          0:00 /usr/bin/node /home/haraka/node_modules/Haraka/haraka.js -c /home/haraka/haraka
```

log output for `nodes=0` also looks good.
not actually serving mail yet, so haven't tested that. let me know if want me to confirm that.

**Comment by tomscytale** [comment]
oh wait - `smtp.ini` has a `daemonize ` option - should that be used instead?

**Comment by msimerson** [comment]
Haraka can be started either way. Systemd can accommodate either way. Which is best is the question. In the absence of knowing better, I'd err on the side of trusting that whomever created the `haraka.service` file did know better.

Past that, I would lean towards having haraka _not_ daemonize so that systemd is attached to the main haraka process (like daemontools/supervise tools do) as I'd expect that to be more efficient than polling the process ID, or however systemd monitors daemonized processes.

**Comment by baudehlo** [comment]
In theory the kernel can wait() on any given PID, but yes I agree with the
rest of the sentiment.

**Comment by tomscytale** [comment]
Agreed. In general I think you're best off allowing systemd to fully manage the process - i.e. not using `daemonize` _unless_ it has some specific benefit.

The issue of efficiency isn't really relevant - systemd doesn't do any polling or whatever - it uses cgroups for control, standard `wait()` to track process exit, and attaches output of spawned processes to unix sockets for logging etc.

It's more a matter of simplicity and ease of use.

So unless `daemonize` provides some benifit we should not use it. 

I'll update the PR with a comment to reflect this.

**Pull request merged**
