### PR TITLE
updates for 2.8.18 release

### PR DESCRIPTION
**Pull request by luto**
I was motivated in https://github.com/haraka/Haraka/pull/2361 to get a release going, so here we go ;)

- [x] Start a N-week quiet period
- [x] Update [haraka-tld](https://github.com/haraka/haraka-tld): https://github.com/haraka/haraka-tld/pull/34
- [x] Draft a release on the [releases page](https://github.com/haraka/Haraka/releases) (Save draft)
- Create a PR with:
    - [x] Updated [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md)
    - [x] Bumped version in [package.json](https://github.com/haraka/Haraka/blob/master/package.json)
- [x] Update release date in [Changes](https://github.com/haraka/Haraka/blob/master/Changes)
- [ ] `npm publish`
- [ ] Post `Changes` file on the draft release and publish the release 
- [ ] update [haraka's wikipedia page](https://en.wikipedia.org/wiki/Haraka_(software))
- [ ] Email the mailing list
- [ ] Publish a blog post
- [ ] Edit the /topic on #haraka IRC channel

### CODE REVIEW

**Comment by luto** [comment]
This release is mainly motivated by #2360 (a crash bug).

**Comment by luto** [comment]
@msimerson done. Thanks! :)

**Comment by msimerson** [comment]
````
$ npm publish
+ Haraka@2.8.18
````

**Comment by luto** [comment]
thanks! :tada:

**Pull request merged**
