### PR TITLE
Fix continuations being folded on get_decoded

### LINKED ISSUE #1378: Mail header is splitted into some pieces and add "\n " before being re-concatenated
I have a problem while sending a mail with a long header.
The mail header is splitted into some pieces in `this.header_lines` array (of `transaction.js`) and then re-join in `mailheader.js`. After this step of re-concatenation `"\n "` is added between each element that modify the initial header.

For example: I try to send a mail with following subject: 
`Un longue titre, c'est la dernière vérification. Ça devrait marcher normalement`

The complete header object received:

**Header** {
  **headers**: 
   { received: [ 'from [192.168.70.163] ([192.168.70.163])\n\tby haraka.test (Haraka/1.0.8) with ESMTP id 68E8604A-F6EA-431F-BF43-6F8219215928.1\n\tenvelope-from <sender@systran.fr>;\n\tTue, 08 Mar 2016 09:55:46 +0100\n' ],
     to: [ 'receiver@mailserver.com\n' ],
     from: [ 'sender <sender@systran.fr>\n' ],
     **subject: [ '=?UTF-8?Q?Un_longue_titre=2c_c\'est_la_derni=c3=a8re_v=c3=a9rificati?=\n =?UTF-8?Q?on._=c3=87a_devrait_marcher_normalement?=\n' ]**,
     'message-id': [ '<56DE9392.9060504@systran.fr>\n' ],
     date: [ 'Tue, 8 Mar 2016 09:55:46 +0100\n' ],
     'user-agent': [ 'Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101\n Thunderbird/38.2.0\n' ],
     'mime-version': [ '1.0\n' ],
     'content-type': [ 'text/plain; charset=utf-8; format=flowed\n' ],
     'content-transfer-encoding': [ '7bit\n' ] },
  **headers_decoded**: 
   { received: [ 'from [192.168.70.163] ([192.168.70.163])\n by haraka.test (Haraka/1.0.8) with ESMTP id 68E8604A-F6EA-431F-BF43-6F8219215928.1\n envelope-from <sender@systran.fr>;\n Tue, 08 Mar 2016 09:55:46 +0100' ],
     to: [ 'receiver@mailserver.com' ],
     from: [ 'sender <sender@systran.fr>' ],
     **subject: [ 'Un longue titre, c\'est la dernière vérificati\n on. Ça devrait marcher normalement' ]**,
     'message-id': [ '<56DE9392.9060504@systran.fr>' ],
     date: [ 'Tue, 8 Mar 2016 09:55:46 +0100' ],
     'user-agent': [ 'Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101\n Thunderbird/38.2.0' ],
     'mime-version': [ '1.0' ],
     'content-type': [ 'text/plain; charset=utf-8; format=flowed' ],
     'content-transfer-encoding': [ '7bit' ] },
  **header_list**: 
   [ 'Received: from [192.168.70.163] ([192.168.70.163])\n\tby haraka.test (Haraka/1.0.8) with ESMTP id 68E8604A-F6EA-431F-BF43-6F8219215928.1\n\tenvelope-from <sender@systran.fr>;\n\tTue, 08 Mar 2016 09:55:46 +0100\n',
     'To: receiver@mailserver.com\n',
     'From: sender <sender@systran.fr>\n',
    '**Subject: =?UTF-8?Q?Un_longue_titre=2c_c\'est_la_derni=c3=a8re_v=c3=a9rificati?=\n =?UTF-8?Q?on._=c3=87a_devrait_marcher_normalement?=\n**',
     'Message-ID: <56DE9392.9060504@systran.fr>\n',
     'Date: Tue, 8 Mar 2016 09:55:46 +0100\n',
     'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101\n Thunderbird/38.2.0\n',
     'MIME-Version: 1.0\n',
     'Content-Type: text/plain; charset=utf-8; format=flowed\n',
     'Content-Transfer-Encoding: 7bit\n' ],
  options: undefined }

So:
`headers.subject = "=?UTF-8?Q?Un_longue_titre=2c_c\'est_la_derni=c3=a8re_v=c3=a9rificati?=\n =?UTF-8?Q?on._=c3=87a_devrait_marcher_normalement?=\n"`

As a result:
`headers_decoded.subject = "Un longue titre, c\'est la dernière vérificati\n on. Ça devrait marcher normalement"`

The word **`"vérification"`** is splitted into **`"vérificati\n on"`**.

It's the same issue with other non utf8 encoding mail but only `"\n"` added between splitted subject elements instead of `"\n "`.

I try a quick fix for this issue by patch `mailheader.js` file from [line 26](https://github.com/haraka/Haraka/blob/master/mailheader.js#L26) as below:

```
        if (line.match(/^[ \t]/)) {
            // continuation
            var currLength = this.header_list.length;
            if (this.header_list[currLength - 1].match(/^(Subject:)/i)) {
                if (this.header_list[currLength - 1].match(/^(Subject: =\?UTF-8\?)/i)) {
                    line = line.replace(/^[ \t]|\n$/g, '');
                }
                else {
                    line = line.replace(/\n$/g, '');
                }
                this.header_list[currLength - 1] = this.header_list[currLength - 1].replace(/\n$/, '');
            }
            this.header_list[currLength - 1] += line;
        }
```

instead of:

```
        if (line.match(/^[ \t]/)) {
            // continuation
            this.header_list[this.header_list.length - 1] += line;
        }
```

### PR DESCRIPTION
**Pull request by baudehlo**
Fixes #1378  .

Changes proposed in this pull request:
- Folds continuations into a single space in decoded headers

Checklist:
- [ ] docs updated
- [x] tests updated

### CODE REVIEW

**Comment by baudehlo** [comment]
Sometimes I hate codecov. I fix bugs. I add tests. Coverage goes down. Epic fail.

**Comment by msimerson** [comment]
>> Merging #1406 into master will **increase** coverage by +0.27%

> Sometimes I hate codecov. I fix bugs. I add tests. *Coverage goes down*. Epic fail.

Emphasis added by me. Does not compute...

**Comment by smfreegard** [comment]
> Merging #1406 into master will **decrease** coverage by -0.19% as of e7bfe30

Was in the email that I got....

**Comment by baudehlo** [comment]
Weird. I can show you a screenshot of the reduced coverage.

**Comment by msimerson** [comment]
Interesting. The commit IDs are different...

**Comment by baudehlo** [comment]
OK I can't show the screenshot now, I lost the page. But smf confirmed at least that I'm not going crazy.

**Comment by msimerson** [comment]
In my experience, codecov only reports on a branch once. Push another commit to it, or force push, and you get no update (which is kinda good, I'd hate to have a long thread of posts from codecov).

**Comment by baudehlo** [comment]
But this was one commit.

Anyway I don't care that much - I'd much rather you review the changes and merge (though probably merge the other headers change first).

**Comment by msimerson** [comment]
LGTM

**Pull request merged**
