### PR TITLE
mods to dns_list_base plugin

### PR DESCRIPTION
**Pull request by celesteking**
- introduce global plugin.lookback_is_rejected flag that allows dnsbls that answer on silence testpoint to function.

Some dnsbl (hostkarma.junkemailfilter.com) return so-called blocked status on queries to 127.0.0.1. This change allows such zones to continue functioning.

In your dnsbl plugin:
```js
    plugin.inherits('dns_list_base');

    plugin.load_config();
    plugin.lookback_is_rejected = plugin.cfg.main.lookback_is_rejected;
```

This will need a proper per-zone solution some day.

Checklist:
- [ ] docs updated
- [x] tests updated
- [ ] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

### CODE REVIEW

**Comment by celesteking** [comment]
All this patch submission drama is way harder than I thought. 
I have also added tests, which will increase test time by ~6 sec

**Comment by celesteking** [comment]
Why isn't codecov covering this file?

**Comment by celesteking** [comment]
ping?

**Comment by msimerson** [comment]
> Why isn't codecov covering this file?

Two reasons:
- nodeunit
- Haraka's plugin architecture that runs code in [runInNewContext](https://nodejs.org/dist/latest-v8.x/docs/api/vm.html)

**Comment by msimerson** [comment]
Update: I've been seeing some random test failures (mostly related to npm) in branches other than this one. The errors I've seen in this PR though are specific to DNSBLs:

````
dns_list_base
✔ disable_zone - empty request
✔ disable_zone - testbl1, no zones
✔ disable_zone - testbl1, zones miss
[WARN] [-] [dns_list_base] disabling zone 'testbl1': test result
✔ disable_zone - testbl1, zones hit
✔ lookup - Spamcop, test IP
✔ lookup - Spamcop, unlisted IP
✔ multi - Spamcop
✔ multi - CBL
✔ multi - Spamcop + CBL
✔ multi - Spamcop + CBL + negative result
✔ multi - IPv6 addresses supported
✔ first - positive result
✔ first - negative result
✔ first - each_cb
[INFO] [-] [dns_list_base] re-enabling zone bl.spamcop.net
[INFO] [-] [dns_list_base] re-enabling zone hostkarma.junkemailfilter.com
✔ lookback_is_rejected - zones with quirks pass through when lookback_is_rejected=true
[INFO] [-] [dns_list_base] re-enabling zone hostkarma.junkemailfilter.com
[INFO] [-] [dns_list_base] re-enabling zone bl.spamcop.net
Reloading file: /home/travis/build/haraka/Haraka/config/testPlugin.timeout
✖ lookback_is_rejected - zones with quirks are disabled when lookback_is_rejected=false
Assertion Message: Enabled all zones back? This should not have happened
AssertionError: [ 'bl.spamcop.net', 'hostkarma.junkemailfilter.com' ] deepEqual [ 'bl.spamcop.net' ]
    at Object.deepEqual (/home/travis/build/haraka/Haraka/node_modules/nodeunit/lib/types.js:83:39)
    at zone_disable_test_func.call (/home/travis/build/haraka/Haraka/tests/plugins/dns_list_base.js:237:18)
    at fin_check (/home/travis/build/haraka/Haraka/tests/plugins/dns_list_base.js:206:9)
    at Timeout.setTimeout (/home/travis/build/haraka/Haraka/tests/plugins/dns_list_base.js:214:67)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
````

**Comment by celesteking** [comment]
Have updated the code and squashes the commits.

**Pull request merged**
