### PR TITLE
Update SettingUpOutbound.md

### PR DESCRIPTION
**Pull request by Currerius**

### CODE REVIEW

**Comment by Dexus** [comment]
Wieso öffnest du drei PR und schließt diese wieder? Einfach wäre den offenen einfach upzudaten.

Why do you create three PR and than you close they? You can easy update a PR....

**Comment by Currerius** [comment]
Because I have no idea about PR's ... noob to git and github ... 
nokoos asked for a squash of two commits and I messed it up ... at least I think I did, so I ended up with brute force... closing the PR, deleting the fork, and opening again with a new fork...

Don't ask why it got three... the story of my ignorance gets too long..

**Comment by Dexus** [comment]
Take a look at https://github.com/haraka/Haraka/wiki/Contributing

Von meinem iPhone gesendet

**Comment by Currerius** [comment]
Yes, thank you, Dexus. That would have helped. It is a summary of what I learned the hard/stupid way ...

**Pull request merged**
