### PR TITLE
Fix connection.remote_host and NXDOMAIN result

### PR DESCRIPTION
**Pull request by smfreegard**
The legacy property connection.remote_host was broken by https://github.com/haraka/Haraka/commit/8e412b10f2a3e646165801d6e519028f7e212563 and was undefined if the DNS lookup returned an error.

Additionally, `dns.NXDOMAIN` was incorrect - as per the Node docs, this should be `dns.NOTFOUND`, so it would appear this has been broken since day one.

### CODE REVIEW

**Comment by msimerson** [comment]
Actually, `NXDOMAIN` -> `NOTFOUND` is a rather recent node.js change, so I'd instead have BOTH listed in that case statement. IE:

```js
    case dns.NXDOMAIN:
    case dns.NOTFOUND:
        your_stuff();
```

**Comment by smfreegard** [comment]
Are you sure about that?  I actually looked through the source code of Node 0.10.x and couldn't find NXDOMAIN was valid.

**Comment by msimerson** [comment]
> Are you sure about that?

It wouldn't have come from the node.js source, it was coming from c-ares. There's some big long threads in the node.js docs discussing this change. I give this change a +1 in that thread sometime ago, so yeah, I'm pretty sure.

**Comment by msimerson** [comment]
Also, "oops." Sorry to have broken remote_host setting. Missed that one...

**Comment by smfreegard** [comment]
I've double checked and NXDOMAIN has either never been valid or it was valid on Node < 0.8 as:

`````
[root@relay1 ~]# echo "var dns = require('dns'); console.log(process.version); console.log('NXDOMAIN => ' + dns.NXDOMAIN); console.log('NOTFOUND => ' + dns.NOTFOUND);" | node
v0.8.16
NXDOMAIN => undefined
NOTFOUND => ENOTFOUND
`````

> Also, "oops." Sorry to have broken remote_host setting. Missed that one...

No worries.   It had me doubting my own sanity until I realised what the issue was.

**Comment by msimerson** [comment]
I just double checked too, and the [thread in question](https://github.com/nodejs/node/issues/3891) is actually replacing the node.js customized error (NOTFOUND) with the `actual` IETF specified DNS error (from c-ares). So I had the direction of the change inverted. That thread is currently stalled, but I'd put that case in there now with this PR because it's likely to match in the future.

**Comment by msimerson** [comment]
Amusingly, there's [quite](https://github.com/haraka/Haraka/blob/master/plugins/connect.fcrdns.js#L171) a [few](https://github.com/haraka/Haraka/blob/master/spf.js#L175) places in our code where we've (at _least_ you and I) have been using both for quite a long time.

**Comment by msimerson** [comment]
Ooooohhhhhhhhhhhh. One reason that we'd have gotten NXDOMAIN results sometimes and NOTFOUND errors at other times is because of the use of dns.lookup (which uses getaddrinfo) vs dns.anythingElse which uses c-ares.

We (haraka) have long avoided using dns.lookup, but that likely explains why we've got 22 instances of NXDOMAIN in our source code.

**Comment by smfreegard** [comment]
I think in my case - I always used the rdns_respond function as a boilerplate and when I had issues I added 'ENOTFOUND' instead and bypassed dns.NOTFOUND altogether.

Anyway - I'll add `dns.NXDOMAIN` back in, to preempt the Node change (thanks for the reference).

**Comment by msimerson** [comment]
thanks @smfreegard

**Pull request merged**
