### PR TITLE
Fix for node8, use forked daemon package

### PR DESCRIPTION
**Pull request by Infern1**
Fixes #

Changes proposed in this pull request:
- Use forked daemon package, see here https://github.com/silverwind/droppy/issues/324

### CODE REVIEW

**Comment by baudehlo** [comment]
I'd rather we fix this by specifying a cwd instead.

**Comment by Infern1** [comment]
> I'd rather we fix this by specifying a cwd instead.
As you wish, same method as here: https://github.com/NodeBB/NodeBB/commit/c3a34bf81a8c2c4519612c826c0ce25a0ac86fd3

**Comment by baudehlo** [comment]
Looks good, but has a lint error (trailing comma).

**Comment by gramakri** [comment]
This patch seems to break the tests. Initially, I thought that was just node 6, but it doesn't work for me on on node 8 either.

```
~/tmp/Haraka$ node --version
v8.4.0
~/tmp/Haraka$ npm test

> Haraka@2.8.14 test /home/girish/tmp/Haraka
> node run_tests

loaded TLD files: 1=1534 2=6132 3=2170
loaded 8229 Public Suffixes
~/tmp/Haraka$ git reset --hard HEAD^
HEAD is now at 35929c2 chore(package): update redis to version 2.8.0 (#2033)
~/tmp/Haraka$ npm test

> Haraka@2.8.14 test /home/girish/tmp/Haraka
> node run_tests

loaded TLD files: 1=1534 2=6132 3=2170
loaded 8229 Public Suffixes

config
✔ arrange_args - name
✔ arrange_args - name, type
✔ arrange_args - name, callback
✔ arrange_args - name, callback, options
...
```

**Comment by msimerson** [comment]
Yeah, I added a [fix](https://github.com/haraka/Haraka/pull/2032/commits/de14201fe90c59fd5a28f69bc7d6e3a61ac256c7#diff-78c12f5adc1848d13b1c6f07055d996eR11) for that in my big TLS pr.

**Comment by msimerson** [comment]
> it doesn't work for me on on node 8 either.

Now that's curious. I saw the failure on my desktop with node 6 and assumed it was a 6 -vs- 8 thing. I think I'll revert this PR until we can figure out why that change breaks the test suite.

**Comment by msimerson** [comment]
Unfortunately, even after it's been reverted, there's no way to re-open this PR. We need to address the daemon issue and the method in this PR breaks the test suite (for unknown reasons).

**Comment by msimerson** [comment]
Another possible solution: the daemon module is just 2 functions. We could import them with a fix for cwd. The `daemon` module is unmaintained for years so there's little chance of getting an upstream fix.

**Comment by baudehlo** [comment]
Hey is there any chance that Node has since included this behaviour? If not, then let's either find a maintained solution or import the code and fix it.

**Comment by msimerson** [comment]
If Node had included it, it's not obvious to me which module they stuck it into. Honestly, it seems like something that should __not__ be in node.js. If anything, discarding that functionality entirely and using OS supplied utilities like `daemon` (included on *BSD, Mac OS X, and most Linux distros) or `systemd` or `launchd` seems like a really good default. Beyond the OS utilities for daemons, npm also offers pm2, forever, daemonize, and more.

**Pull request merged**
