### PR TITLE
postgres recipient validation plugin

### PR DESCRIPTION
**Pull request by thihara**
Changes proposed in this pull request:
- New plugin to validate the recipient address through a PostgreSQL database.

Checklist:
- [x] docs updated

see [haraka-plugin-rcpt-postgresql](https://github.com/haraka/haraka-plugin-rcpt-postgresql)

### CODE REVIEW

**Comment by thihara** [comment]
Could someone tell me what's making the CI job fail?

**Comment by Dexus** [comment]
That you don't use our coding standards. 

Von meinem iPhone gesendet

**Comment by msimerson** [comment]
# Required fixes

1. [ ] [lint errors](https://travis-ci.org/haraka/Haraka/jobs/171933102). See that little red X next to your commits? Click on it. It'll lead you to the build test, which details the problems.
2. [ ] vague plugin name. We've already got several plugins name `rcpt_to.*` and **ALL** of them test recipient validity. Rename your plugin to something like `rcpt_to.postgres` that describes *how* it determines validity, and how that's distinct from the other plugins that determine recipient validity.

**Comment by thihara** [comment]
Got it guys, I have been swamped in the office these few days, I'll do the changes over the weekend.

**Comment by thihara** [comment]
@msimerson Done. Please review.

**Comment by msimerson** [comment]
Much better @thihara 

The next and final issue is dealing with the dependency on `pg`.  There's a tension between:

* add to package.json and deal everyone having to install it
    * con: installs take longer
    * con: overall install becomes more fragile
* don't add to package.json, and require users to install it manually
    * con: crashes hard when users enable the plugin without installing `pg`
        * this can be addressed by using try/catch around the `require('pg')`

Currently, our preferred way to handle this issue is to create a separate npm module named like [haraka-plugin-rcpt-postgresql](https://github.com/haraka/haraka-plugin-rcpt-postgresql). This provides a few advantages:
* explicit declaration of `pg` dependency in package.json
* the module can/should be installed in Haraka's install (haraka -i) dir, so it's preserved across Haraka install/upgrades.

**Comment by msimerson** [comment]
Hey @thihara, I've created the repo [haraka-plugin-rcpt-postgresql](https://github.com/haraka/haraka-plugin-rcpt-postgresql) and added all the boilerplate needed for an NPM module. I haven't put your files in there because I want you to get the credit for authoring it. So, here's what I have for you to do:

1. clone that repo
2. mkdir config
3. cp ../haraka/config/rcpt_to.postgresql.json config/
4. cat ../haraka/docs/plugins/rcpt_to.postgresql.md >> README.md
5. remote the dependencies clause from README.md (it's explicit now, in package.json)
6. cp ../haraka/plugins/rcpt_to.postgresql.js index.js
7. add an `install` section to README.md (see [log-reader](https://github.com/haraka/haraka-plugin-log-reader) for an example

That should be enough to get the plugin all packaged up and ready to publish to NPM.

**Comment by msimerson** [comment]
I've also created a couple tests. After you import the config and main plugin file, the tests should pass on your PR. You can also add additional tests if you're so inclined. Some really GREAT tests to add would be [setting up a postgres DB](https://docs.travis-ci.com/user/database-setup/#PostgreSQL) and then authenticating against it.

**Comment by thihara** [comment]
@msimerson  Build failing on travis `  50:18  error  'DENY' is not defined  no-undef`, it's a lint error and is due to the `next(DENY, "Message")` in the plugin.

Suggestions?

**Comment by msimerson** [comment]
Ah, import haraka-constants and change 'DENY' to 'constants.DENY'.

```js
var constants = require('haraka-constants');
.... constants.DENY;
```

**Pull request closed without merging**
