### PR TITLE
Added missing 'default' keyword in rspamd plugin. Score wasn't added …

### PR DESCRIPTION
**Pull request by gtech99**
r.data which contains the rspamd answer also contains the 'default' index which was omitted by the author in a few places. Because of this, scores weren't added properly to headers.

### CODE REVIEW

**Comment by msimerson** [comment]
Did the code you're changing never work correctly? Does it only work correctly with some versions of rspamd? 

There are tests in place that suggest the code used to work as intended, and your changes break them. Either your changes aren't correct, or the tests must be updated.

**Comment by gtech99** [comment]
I need to update the tests as well. The code never worked correctly.

 

George

**Comment by swerter** [comment]
+1 R-Spamd score is now added correctly

**Comment by gtech99** [comment]
modified ES logging of envelope/recipients as lowercase

**Comment by gtech99** [comment]
Fixed rspamd tests

**Comment by msimerson** [comment]
Looks good, thanks @gtech99

**Pull request merged**
