### PR TITLE
Allow streams in outbound.send_email contents

### LINKED ISSUE #1549: outbound.send_email accept stream
Hi.

We use Haraka for processing the email, make some changes, and send it again.

For doing that we use the `connection.transaction.message_stream.pipe`.
When we ended the modifications we send using `outbound.send_email`. However `outbound.send_email` only accepts a string, so we do something like
````js
outbound.send_email(connection.transaction.mail_from, connection.transaction.rcpt_to, message.toString(), function (code, msg) {});
````

As you see, we conver the stream to string, and you know that could be very memory intensive with large attachments.

Would you please allow send a stream?

Thanks!!

### PR DESCRIPTION
**Pull request by baudehlo**
Fixes #1549  .

Changes proposed in this pull request:
- Allow send_email to use a stream in the `contents` object

Checklist:
- [ ] docs updated
- [ ] tests updated

### CODE REVIEW

**Comment by ricardopolo** [comment]
Does not work :disappointed: 

image


The testing code was like this:
````js
mailcomposer(mail_options).build(function(err, messageStream){
   outbound.send_email(connection.transaction.mail_from, connection.transaction.rcpt_to, messageStream, function (code, msg) {
````

**Comment by baudehlo** [comment]
From the docs of mailcomposer, that's not how you get a stream. Your code should be:
```javascript
var stream = mailcomposer(mail_options).createReadStream();
outbound.send_email(connection.transaction.mail_from, connection.transaction.rcpt_to, stream, function (code, msg) {
```

**Comment by ricardopolo** [comment]
@baudehlo not working yet.

Using this code:

````js
connection.loginfo("Before Stream");
var stream = mailcomposer(mail_options).createReadStream();
connection.loginfo("After Stream");
outbound.send_email(connection.transaction.mail_from, connection.transaction.rcpt_to, stream, function (code, msg) {
              connection.loginfo("After Send Email");
````


This is the output (After sending with the stream Haraka Stops, and never shows "After Send Email"")
image

**Comment by baudehlo** [comment]
Can you try adding a stream.resume() to the end of the stream_line_reader
function?

**Comment by ricardopolo** [comment]
Excuse me @baudehlo but I did not find a `stream_line_reader` function... any help?

**Comment by baudehlo** [comment]
It's here in outbound.js:
https://github.com/haraka/Haraka/blob/c22548e7a784a7818388c7457e8cef39b89f5d69/outbound.js#L533

You are using the right branch I hope?

**Comment by ricardopolo** [comment]
I did it. Same behavior

image

**Comment by ricardopolo** [comment]
@ImLostInSpace the issue persists...

screen shot 2016-09-02 at 5 15 27 pm

**Comment by baudehlo** [comment]
Yes the commit wasn't designed to fix anything. It was just lying around on
my disk waiting to be pushed.

I need to write some code to test this to figure out what's going on. Maybe
this weekend.

**Comment by baudehlo** [comment]
Should work now.

**Comment by ricardopolo** [comment]
Great!!! It works!!! Thank you so much!
:shipit:

**Pull request merged**
