### PR TITLE
release Haraka 2.8.21

### PR DESCRIPTION
**Pull request by msimerson**
Changes proposed in this pull request:
- transaction: flow & style improvements
- transaction: improve whitespace and comments
- messagestream: rename config => cfg (for consistency)
- update Changes.md
- bump Haraka version

Checklist:
- [x] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

### CODE REVIEW

**Comment by msimerson** [comment]
- [ ] Start a N-week quiet period
- [x] Update [haraka-tld](https://github.com/haraka/haraka-tld)
- [ ] Draft a release on the [releases page](https://github.com/haraka/Haraka/releases) (Save draft)
- Create a PR with:
    - [ ] Updated [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md)
    - [ ] Bumped version in [package.json](https://github.com/haraka/Haraka/blob/master/package.json)
- For major version releases:
    * [ ] check for waiting PRs for that milestone version.
    * [ ] Grep the source for: `Sunset v3`, where 3 is the new major version.
- [ ] Update release date in [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md)
- [ ] `npm publish`
- [ ] Post `Changes` file on the draft release and publish the release 
- [ ] update [haraka's wikipedia page](https://en.wikipedia.org/wiki/Haraka_(software))
- [ ] Email the mailing list
- [ ] Publish a blog post
- [ ] Edit the /topic on #haraka IRC channel

**Comment by msimerson** [comment]
fixes #2490

**Comment by msimerson** [comment]
Are there any objections to releasing today?

**Comment by msimerson** [comment]
I did a test deploy yesterday on a production system and everything appeared to be working fine. The only real issue outstanding I'm aware of is @baudehlo possibly wanting to get #2482 merged, but I get the sense it needs more attention before it's ready.

**Comment by baudehlo** [comment]
/shrug it just needed someone to sanity check it. Nobody did.

**Comment by smfreegard** [comment]
Sorry - that was my fault.   I didn't realise you were waiting on it for a release otherwise I would have tried a bit harder ;-)

**Comment by msimerson** [comment]
````
$ npm publish
+ Haraka@2.8.21
````

**Pull request merged**
