### PR TITLE
smtp_forward: tighten up queue.wants routing

### PR DESCRIPTION
**Pull request by msimerson**
Changes proposed in this pull request:
- smtp_forward: tighten up queue.wants routing
- doc(smtp_forward): improve markdown formatting

Checklist:
- [x] docs updated
- [x] tests updated
- [x] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

### CODE REVIEW

**Comment by gramakri** [comment]
To add some more info, the way we configure the forwad plugin is:

```
enable_outbound=false
domain_selector=mail_from
[cloudron.addon]
enable_outbound=true
host=172.18.0.1
port=2587
enable_tls=true
auth_type=plain
auth_user=relay_user
auth_pass=relay_pass
```

With the above config, emails are not forwarded to the relay.

**Comment by msimerson** [comment]
>  if enable_outbound is false. Is this intentional ?

Well yes. Sorry. The `get_mx` hook doesn't forward (in the sense of the smtp_forward plugin) at all. Instead, messages are accepted into Haraka's queue and then delivered with outbound. The `get_mx` hook _can_ then provide a more specific route to outbound. But it's really not forwarding, it's MX routing, right? And so get_mx should be controlled by outbound_enabled.

That's what I was thinking. But I missed something important: that disables the ability to have [outbound] forward MX routing disabled in the main config and enabled per-domain. And vise versa. #3204 does the needful, but it needs to have a test added so prevent future regressions. smtp_forward is used in quite a few ways (I also [ab]use it to deliver via LMTP using outbound).

**Comment by gramakri** [comment]
> But I missed something important: that disables the ability to have [outbound] forward MX routing disabled in the main config and enabled per-domain

Yes, indeed, this is exactly how we were using it. I see you already reverted that part of the code, thanks! I will test and get back.

**Comment by gramakri** [comment]
Can confirm your revert fixed the issue (for us).

**Pull request merged**
