### PR TITLE
No watch files plugin order

### PR DESCRIPTION
**Pull request by baudehlo**
Disables watch_files when asking for plugin run order.

### CODE REVIEW

**Comment by baudehlo** [comment]
This PR looks so horrendous because I didn't realise my upstream was wrong (baudehlo/Haraka instead of haraka/Haraka). Hopefully github squishing the commit will make it perty.

**Comment by baudehlo** [comment]
Failures appear to be in SPF which appear completely unrelated btw.

To replicate this issue, do `haraka -o -c /some/invalid/path`.

**Comment by msimerson** [comment]
I've fixed the SPF issue in #1409 . If you [rebase](https://github.com/haraka/Haraka/wiki/Contributing#rebase) this against haraka/master, it'll clean up the commit log and pass tests.

**Comment by baudehlo** [comment]
I thought rebase wasn't required any more with the recent GitHub update?

**Comment by msimerson** [comment]
> I thought rebase wasn't required any more with the recent GitHub update?

We'll see. I just clicked the "Update branch" button and it's running tests again.

**Pull request merged**
