### PR TITLE
Converted Clamd.js file to ES6

### PR DESCRIPTION
**Pull request by Hari70a**
Fixes #

Changes proposed in this pull request:
- 
- 

Checklist:
- [ ] docs updated
- [ ] tests updated
- [ ] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

### CODE REVIEW

**Comment by Hari70a** [comment]
@pvsousalima 
Can u please review this

**Comment by msimerson** [comment]
Click the details links next to failing CI tests. If tests won't pass, we don't bother to review and your PR isn't eligible to be merged.

**Comment by msimerson** [comment]
You can run `npm run lint` locally in your branch to see the issues.

**Comment by msimerson** [comment]
There's still a couple issues here.
- You've created the file ./clamd.js, when you want to be update tests/plugins/clamd.js.
- the other is a lint error:
    - 1:1 error Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by msimerson** [comment]
Closing as incorrect and abandoned.

**Pull request closed without merging**
