### PR TITLE
Address potential CWE in connection.js

### PR DESCRIPTION
**Pull request by unquietwiki**
Attempts to resolve CWE issue discovered in #3135 work.

- https://cwe.mitre.org/data/definitions/484
- https://rules.sonarsource.com/javascript/RSPEC-128

**Edit:** I had a typo in this process; I meant CWE, not CVE.

### CODE REVIEW

**Comment by msimerson** [comment]
I read the links. I disagree. Strongly.  Simply because a switch/case can fall through inadvertently does not mean that any uses of switch case that purposefully use that behavior are somehow wrong or vulnerable. Fine, give them some extra scrutiny if you wish, but this is change for changes sake and I find the replacement code to be considerably less legible.

**Comment by unquietwiki** [comment]
Thank you. This is my last submission for the time being; I look forward to 3.0.

**Comment by unquietwiki** [comment]
Hey, I was looking at the open issues, and found #3023: could this be related at all?

**Comment by unquietwiki** [comment]
I had a call with the dev of https://rubberduck.tech/ this morning. I tried running the old and new code through it: it said they were comparable in function, so that's somewhat helpful; he also thought both solutions were readable. Another friend of mine dislikes the original method here, but thought he could do better than what I tried: he was thinking of combining some of the tests, but I had tried that before without passing the readability test here.

**Pull request closed without merging**
