### PR TITLE
Now passing options parameter to MessageStream get_data

### PR DESCRIPTION
**Pull request by ricardopolo**
There is a bug in `get-data` of `messagestram`.

Currently if you pass the options parameter they are ignored. 

You can confirm it here, and test the pruposed fix https://repl.it/BgLr/0

So this PR fixes it. Tested for passing just the callback and the options and callback.

### CODE REVIEW

**Comment by ricardopolo** [comment]
@msimerson any comments about this?

**Comment by msimerson** [comment]
Your change looks good. I have to admit I don't understand *why* the current code there doesn't work, and before reviewing your proposed code, I couldn't see the bug. Now I can, but I still don't know why, and that annoys me. I'd much rather see test coverage added to cover this, but if you get this rebased (post a comment after), I'll merge it, even without tests.

**Comment by msimerson** [comment]
@ricardopolo, still waiting for you to [rebase](https://github.com/haraka/Haraka/wiki/Contributing#rebase) this so it can get merged.

**Comment by ricardopolo** [comment]
@msimerson Sorry for the delay, tomorrow I'll create the test

**Pull request merged**
