### PR TITLE
Add process, transaction, SMT Response, respond..

### PR DESCRIPTION
**Pull request by MuraraAllan**
Add process_line, process_line, process_data, _process_data, respond, fail, disconnect, disconnect_respond, get_capabilities,  tran_uuid, reset_transaction, init_transaction, loop_responide, pause, resume, SMT Responses module.

Resuming #2166
 
Fixes #

Changes proposed in this pull request:
- 
- 

Checklist:
- [ ] docs updated
- [ ] tests updated
- [ ] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

### CODE REVIEW

**Comment by MuraraAllan** [comment]
Trying to label with work in progress but i don't get the option. Is it exclusive to contributors?

**Comment by MuraraAllan** [comment]
The job is finished feel free to close.

**Comment by baudehlo** [comment]
You can add &w=1 to the URL manually for that.

**Comment by msimerson** [comment]
No way!? That'd be fantastic. But it [doesn't seem to work](https://github.com/haraka/Haraka/pull/2173/files&w=1) for PRs.

**Comment by baudehlo** [comment]
It does, but it's ?w=1 not &w=1

**Comment by KingNoosh** [comment]
It works, add a `?w=1` you case since it's first query param

**Comment by msimerson** [comment]
Ahhh, FAN-PANCAKE-FLIPPING-TASTIC! Thanks guys.

**Pull request merged**
