### PR TITLE
Add ability to hide (Haraka/x.x.x) in headers.  Closes GH-1448.

### PR DESCRIPTION
**Pull request by darkpixel**
Fixes # 1448

Changes proposed in this pull request:
- If a file exists in the config directory 'header_hide_version', do not put the Haraka version number into the received headers.

Checklist:
- [ ] docs updated
- [ ] tests updated

### CODE REVIEW

**Comment by msimerson** [comment]
I'm wondering if the better way to address this may be to create a header_string file, or a header_string property in smtp.ini and have template variables in it that get replaced. Then the received header can be customized much further my editing a config file, and it's less likely to be affected by future Haraka upgrades.

**Comment by darkpixel** [comment]
```
Received: from some.server.tld (some.server.tls
        [1.2.3.4])       by my.mailserver.tls (Haraka/2.7.3) with ESMTP id
        4C0675D5-240D-4015-A0AC-01B2C15E2A35.1  envelope-from
        <joe@server.tls>;       Thu, 05 May 2016 12:47:54 -0700
```

I can understand wanting to remove the version string, but what else would you want to remove out of there?  The header format is pretty standard in debugging and tracking down problems.

Note: I'm not familiar enough with the RFCs to know whether there is a standard header format or not.

**Comment by msimerson** [comment]
> what else would you want to remove out of there?

Off the top of my head, things I've seen other MTAs put there, and other things some don't want included:

* MTA
* MTA version
* TLS info
* TLS protocol
* AUTH info (user)

There's been plenty of conversations about this in the QP mailing list, with a diversity of opinions about what should and should not be included, for various reasons. Perhaps a reasonable way to describe it is that including more data is beneficial for debugging and less is beneficial for security. Each organization has their priorities and making the received header so customizable would avoid future bike shed discussions on the matter.

**Comment by ricardopolo** [comment]
Do agree with @msimerson. Every user should be able to decide what put in here :)

**Comment by darkpixel** [comment]
I agree.  Unfortunately I'm still a n00b when it comes to nodejs/javascript.  No guarantees on when it'll be ready.  ;)

**Comment by baudehlo** [comment]
Any objections from the team for merging this?

**Comment by ricardopolo** [comment]
In my opinion could be better if you can customize what do you want to show... but... meanwhile If it was my decision I would approved this PR :)

And maybe later work in the full customization

**Comment by msimerson** [comment]
+1 to what @ricardopolo said.

**Comment by baudehlo** [comment]
Merge away. I want to get 2.8.1 out asap.

**Pull request merged**
