### PR TITLE
Ssl shutdown bug

### PR DESCRIPTION
**Pull request by baudehlo**
I'm only PR'ing this to wonder why it never got merged, and see if it's potentially still an issue. I was just going through branches on GH and saw this and figured it deserved a look at.

### CODE REVIEW

**Comment by Dexus** [comment]
This bug is 2 years old i have seen your report on node.js 0.10.2x release.

I cant find any doc about the shutdown...

Von meinem iPhone gesendet

**Comment by baudehlo** [comment]
So it's fixed in newer versions of node?

**Comment by Dexus** [comment]
I will tomorrow take a look, never have seen there a bug, so i don't know details now.

Von meinem iPhone gesendet

> Am 11.06.2016 um 01:12 schrieb Matt Sergeant <notifications@github.com>:
> 
> So it's fixed in newer versions of node?
>

**Comment by Dexus** [comment]
So after my research, i can't find any open bugs that since your report on the old node repo. So it looks fixed.

**Comment by baudehlo** [comment]
OK, closing and deleting branch.

**Pull request closed without merging**
