### PR TITLE
release 2.8.22

### LINKED ISSUE #2519: [outbound] Oops, TLS config not loaded yet!
### system info

Haraka | Haraka.js — Version: 2.8.21
 --- | :--- 
Node | v6.14.3
OS | Linux smtp1.raclus.net 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2k-fips  26 Jan 2017

### Expected behavior
TLS Suppor enabled

### Observed behavior
Haraka is throwing errr "[outbound] Oops, TLS config not loaded yet!" when enable nodes=cpus in smtp.ini

### Steps to reproduce
Enable nodes=cpus in smtp.ini
If I disable nodes=cpus all works fine

### My smtp.ini config file (no comments)
listen=0.0.0.0:587
user=mail
group=mail
nodes=cpus

### My tls.ini config file
key=certs/key.pem
cert=certs/cert.pem
dhparam=certs/dhparams.pem
ciphers=ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4

key, cert and dhparam files are in certs directory

### PR DESCRIPTION
**Pull request by msimerson**
- fixes #2519
- [x] Start a N-week quiet period
- [x] Update [haraka-tld](https://github.com/haraka/haraka-tld)
- [x] Draft a release on the [releases page](https://github.com/haraka/Haraka/releases) (Save draft)
- Create a PR with:
    - [x] Updated [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md)
    - [x] Bumped version in [package.json](https://github.com/haraka/Haraka/blob/master/package.json)
- [x] Update release date in [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md)
- [ ] `npm publish`
- [ ] Post `Changes` file on the draft release and publish the release 
- [ ] update [haraka's wikipedia page](https://en.wikipedia.org/wiki/Haraka_(software))
- [ ] Email the mailing list
- [ ] Publish a blog post
- [ ] Edit the /topic on #haraka IRC channel

### CODE REVIEW

**Comment by msimerson** [comment]
Any objections to cutting a release?

**Comment by baudehlo** [comment]
None here. I would like to figure out these LMTP issues but it’s not a blocker.

**Comment by msimerson** [comment]
````
$ npm publish
npm notice 
npm notice 📦  Haraka@2.8.22
npm notice === Tarball Contents === 
npm notice 3.1kB  package.json                                                   
npm notice 105B   .editorconfig                                                  
npm notice 161B   .eslintrc.yaml                                                 
npm notice 0      .gitmodules                                                    
npm notice 674B   .travis.yml                                                    
npm notice 385B   appveyor.yml                                                   
npm notice 2.8kB  attachment_stream.js                                           
npm notice 46.4kB Changes.md                                                     
npm notice 2.3kB  chunkemitter.js                                                
npm notice 257B   config.js                                                      
npm notice 70.8kB connection.js                                                  
npm notice 55B    CONTRIBUTING.md                                                
npm notice 21.1kB dkim.js                                                        
npm notice 1.7kB  Dockerfile                                                     
npm notice 2.1kB  haraka.js                                                      
npm notice 48B    haraka.sh                                                      
npm notice 5.5kB  host_pool.js                                                   
npm notice 1.1kB  LICENSE                                                        
npm notice 1.3kB  line_socket.js                                                 
npm notice 9.1kB  logger.js                                                      
npm notice 16.7kB mailbody.js                                                    
npm notice 9.1kB  mailheader.js                                                  
npm notice 14.5kB messagestream.js                                               
npm notice 18.9kB plugins.js                                                     
npm notice 12.9kB Plugins.md                                                     
npm notice 5.0kB  README.md                                                      
npm notice 3.1kB  rfc1869.js                                                     
npm notice 609B   run_tests                                                      
npm notice 20.3kB server.js                                                      
npm notice 20.9kB smtp_client.js                                                 
npm notice 26.9kB spf.js                                                         
npm notice 21.3kB tls_socket.js                                                  
npm notice 1.7kB  TODO                                                           
npm notice 6.6kB  transaction.js                                                 
npm notice 1.6kB  .github/CONTRIBUTING.md                                        
npm notice 377B   .github/ISSUE_TEMPLATE.md                                      
npm notice 186B   .github/PULL_REQUEST_TEMPLATE.md                               
npm notice 974B   bin/dkimverify                                                 
npm notice 392B   bin/haraka_grep                                                
npm notice 1.2kB  bin/spf                                                        
npm notice 527B   config/access.domains                                          
npm notice 4B     config/aliases                                                 
npm notice 19B    config/attachment.ctype.regex                                  
npm notice 137B   config/attachment.filename.regex                               
npm notice 45B    config/auth_flat_file.ini                                      
npm notice 134B   config/auth_vpopmaild.ini                                      
npm notice 72B    config/avg.ini                                                 
npm notice 261B   config/bounce.ini                                              
npm notice 2.0kB  config/data.headers.ini                                        
npm notice 2.4kB  config/data.uribl.excludes                                     
npm notice 704B   config/data.uribl.ini                                          
npm notice 9B     config/databytes                                               
npm notice 234B   config/delay_deny.ini                                          
npm notice 143B   config/dkim_sign.ini                                           
npm notice 2.0kB  config/dkim/dkim_key_gen.sh                                    
npm notice 606B   config/dnsbl.ini                                               
npm notice 167B   config/early_talker.ini                                        
npm notice 766B   config/greylist.ini                                            
npm notice 1.3kB  config/helo.checks.ini                                         
npm notice 61B    config/host_list                                               
npm notice 306B   config/host_list_regex                                         
npm notice 217B   config/http.ini                                                
npm notice 78B    config/lmtp.ini                                                
npm notice 271B   config/log.ini                                                 
npm notice 322B   config/lookup_rdns.strict.ini                                  
npm notice 2B     config/lookup_rdns.strict.timeout                              
npm notice 65B    config/lookup_rdns.strict.whitelist                            
npm notice 352B   config/lookup_rdns.strict.whitelist_regex                      
npm notice 93B    config/mail_from.is_resolvable.ini                             
npm notice 3B     config/max_unrecognized_commands                               
npm notice 242B   config/messagesniffer.ini                                      
npm notice 414B   config/outbound.bounce_message                                 
npm notice 1.3kB  config/outbound.bounce_message_html                            
npm notice 7.9kB  config/outbound.bounce_message_image                           
npm notice 591B   config/outbound.ini                                            
npm notice 1.7kB  config/plugins                                                 
npm notice 207B   config/rabbitmq_amqplib.ini                                    
npm notice 188B   config/rabbitmq.ini                                            
npm notice 66B    config/rcpt_to.blocklist                                       
npm notice 0      config/rdns.allow_regexps                                      
npm notice 0      config/rdns.deny_regexps                                       
npm notice 46B    config/smtp_bridge.ini                                         
npm notice 459B   config/smtp_forward.ini                                        
npm notice 331B   config/smtp_proxy.ini                                          
npm notice 1.4kB  config/smtp.ini                                                
npm notice 1.3kB  config/spamassassin.ini                                        
npm notice 34B    config/spf.ini                                                 
npm notice 2B     config/tarpit.timeout                                          
npm notice 1.7kB  config/tls.ini                                                 
npm notice 451B   config/watch.ini                                               
npm notice 65B    config/xclient.hosts                                           
npm notice 595B   contrib/bad_smtp_server.pl                                     
npm notice 154B   contrib/Haraka.cf                                              
npm notice 1.6kB  contrib/haraka.init                                            
npm notice 865B   contrib/Haraka.pm                                              
npm notice 456B   contrib/haraka.service                                         
npm notice 2.8kB  contrib/plugin2npm.sh                                          
npm notice 580B   contrib/ubuntu-upstart/haraka.conf                             
npm notice 582B   docs/Body.md                                                   
npm notice 90B    docs/Config.md                                                 
npm notice 2.2kB  docs/Connection.md                                             
npm notice 5.9kB  docs/CoreConfig.md                                             
npm notice 102B   docs/CustomReturnCodes.md                                      
npm notice 316B   docs/deprecated/data.nomsgid.md                                
npm notice 433B   docs/deprecated/data.noreceived.md                             
npm notice 464B   docs/deprecated/data.rfc5322_header_checks.md                  
npm notice 2.6kB  docs/deprecated/lookup_rdns.strict.md                          
npm notice 606B   docs/deprecated/mail_from.blocklist.md                         
npm notice 350B   docs/deprecated/mail_from.nobounces.md                         
npm notice 597B   docs/deprecated/rcpt_to.blocklist.md                           
npm notice 1.3kB  docs/deprecated/rdns.regexp.md                                 
npm notice 2.7kB  docs/HAProxy.md                                                
npm notice 1.4kB  docs/Header.md                                                 
npm notice 2.7kB  docs/Logging.md                                                
npm notice 15.0kB docs/Outbound.md                                               
npm notice 16.4kB docs/Plugins.md                                                
npm notice 104B   docs/plugins/access.md                                         
npm notice 5.9kB  docs/plugins/aliases.md                                        
npm notice 2.7kB  docs/plugins/attachment.md                                     
npm notice 1.1kB  docs/plugins/auth/auth_bridge.md                               
npm notice 1.6kB  docs/plugins/auth/auth_ldap.md                                 
npm notice 1.7kB  docs/plugins/auth/auth_proxy.md                                
npm notice 1.2kB  docs/plugins/auth/auth_vpopmaild.md                            
npm notice 1.5kB  docs/plugins/auth/flat_file.md                                 
npm notice 1.4kB  docs/plugins/avg.md                                            
npm notice 438B   docs/plugins/backscatterer.md                                  
npm notice 704B   docs/plugins/block_me.md                                       
npm notice 2.1kB  docs/plugins/bounce.md                                         
npm notice 4.1kB  docs/plugins/clamd.md                                          
npm notice 2.3kB  docs/plugins/connect.rdns_access.md                            
npm notice 3.0kB  docs/plugins/data.headers.md                                   
npm notice 351B   docs/plugins/data.signatures.md                                
npm notice 3.8kB  docs/plugins/data.uribl.md                                     
npm notice 749B   docs/plugins/delay_deny.md                                     
npm notice 3.1kB  docs/plugins/dkim_sign.md                                      
npm notice 638B   docs/plugins/dkim_verify.md                                    
npm notice 2.5kB  docs/plugins/dnsbl.md                                          
npm notice 2.3kB  docs/plugins/dnswl.md                                          
npm notice 732B   docs/plugins/early_talker.md                                   
npm notice 273B   docs/plugins/esets.md                                          
npm notice 3.3kB  docs/plugins/greylist.md                                       
npm notice 3.5kB  docs/plugins/helo.checks.md                                    
npm notice 2.2kB  docs/plugins/mail_from.access.md                               
npm notice 785B   docs/plugins/mail_from.is_resolvable.md                        
npm notice 801B   docs/plugins/max_unrecognized_commands.md                      
npm notice 6.6kB  docs/plugins/messagesniffer.md                                 
npm notice 760B   docs/plugins/prevent_credential_leaks.md                       
npm notice 2.1kB  docs/plugins/process_title.md                                  
npm notice 102B   docs/plugins/queue/deliver.md                                  
npm notice 721B   docs/plugins/queue/discard.md                                  
npm notice 590B   docs/plugins/queue/lmtp.md                                     
npm notice 458B   docs/plugins/queue/qmail-queue.md                              
npm notice 2.9kB  docs/plugins/queue/quarantine.md                               
npm notice 908B   docs/plugins/queue/rabbitmq_amqplib.md                         
npm notice 1.1kB  docs/plugins/queue/rabbitmq.md                                 
npm notice 1.0kB  docs/plugins/queue/smtp_bridge.md                              
npm notice 4.3kB  docs/plugins/queue/smtp_forward.md                             
npm notice 1.9kB  docs/plugins/queue/smtp_proxy.md                               
npm notice 2.2kB  docs/plugins/rcpt_to.access.md                                 
npm notice 1.3kB  docs/plugins/rcpt_to.in_host_list.md                           
npm notice 219B   docs/plugins/rcpt_to.max_count.md                              
npm notice 145B   docs/plugins/rcpt_to.routes.md                                 
npm notice 715B   docs/plugins/record_envelope_addresses.md                      
npm notice 951B   docs/plugins/relay_acl.md                                      
npm notice 565B   docs/plugins/relay_all.md                                      
npm notice 621B   docs/plugins/relay_force_routing.md                            
npm notice 6.9kB  docs/plugins/relay.md                                          
npm notice 845B   docs/plugins/reseed_rng.md                                     
npm notice 3.4kB  docs/plugins/spamassassin.md                                   
npm notice 4.6kB  docs/plugins/spf.md                                            
npm notice 1.8kB  docs/plugins/tarpit.md                                         
npm notice 5.8kB  docs/plugins/tls.md                                            
npm notice 794B   docs/plugins/toobusy.md                                        
npm notice 283B   docs/plugins/xclient.md                                        
npm notice 178B   docs/Results.md                                                
npm notice 5.5kB  docs/Transaction.md                                            
npm notice 9.1kB  docs/Tutorial.md                                               
npm notice 4.5kB  docs/tutorials/Migrating_from_v1_to_v2.md                      
npm notice 3.0kB  docs/tutorials/SettingUpOutbound.md                            
npm notice 472B   http/bower.json                                                
npm notice 2.2kB  http/Gruntfile.js                                              
npm notice 1.3kB  http/html/index.html                                           
npm notice 312B   http/package.json                                              
npm notice 6.7kB  outbound/client_pool.js                                        
npm notice 1.4kB  outbound/config.js                                             
npm notice 1.1kB  outbound/fsync_writestream.js                                  
npm notice 59.7kB outbound/hmail.js                                              
npm notice 11.4kB outbound/index.js                                              
npm notice 1.8kB  outbound/mx_lookup.js                                          
npm notice 3.2kB  outbound/qfile.js                                              
npm notice 11.8kB outbound/queue.js                                              
npm notice 1.7kB  outbound/timer_queue.js                                        
npm notice 3.3kB  outbound/tls.js                                                
npm notice 433B   outbound/todo.js                                               
npm notice 147B   plugins/.eslintrc.yaml                                         
npm notice 3.6kB  plugins/aliases.js                                             
npm notice 18.1kB plugins/attachment.js                                          
npm notice 9.5kB  plugins/auth/auth_base.js                                      
npm notice 567B   plugins/auth/auth_bridge.js                                    
npm notice 134B   plugins/auth/auth_ldap.js                                      
npm notice 8.3kB  plugins/auth/auth_proxy.js                                     
npm notice 4.8kB  plugins/auth/auth_vpopmaild.js                                 
npm notice 1.2kB  plugins/auth/flat_file.js                                      
npm notice 5.9kB  plugins/avg.js                                                 
npm notice 779B   plugins/backscatterer.js                                       
npm notice 2.6kB  plugins/block_me.js                                            
npm notice 14.6kB plugins/bounce.js                                              
npm notice 13.0kB plugins/clamd.js                                               
npm notice 138B   plugins/connect.asn.js                                         
npm notice 141B   plugins/connect.fcrdns.js                                      
npm notice 142B   plugins/connect.geoip.js                                       
npm notice 143B   plugins/connect.p0f.js                                         
npm notice 4.0kB  plugins/connect.rdns_access.js                                 
npm notice 14.6kB plugins/data.headers.js                                        
npm notice 425B   plugins/data.nomsgid.js                                        
npm notice 620B   plugins/data.noreceived.js                                     
npm notice 1.0kB  plugins/data.rfc5322_header_checks.js                          
npm notice 785B   plugins/data.signatures.js                                     
npm notice 15.1kB plugins/data.uribl.js                                          
npm notice 5.2kB  plugins/delay_deny.js                                          
npm notice 11.4kB plugins/dkim_sign.js                                           
npm notice 1.8kB  plugins/dkim_verify.js                                         
npm notice 7.3kB  plugins/dns_list_base.js                                       
npm notice 4.2kB  plugins/dnsbl.js                                               
npm notice 1.9kB  plugins/dnswl.js                                               
npm notice 3.5kB  plugins/early_talker.js                                        
npm notice 2.5kB  plugins/esets.js                                               
npm notice 145B   plugins/graph.js                                               
npm notice 20.7kB plugins/greylist.js                                            
npm notice 18.5kB plugins/helo.checks.js                                         
npm notice 121B   plugins/log.syslog.js                                          
npm notice 6.4kB  plugins/lookup_rdns.strict.js                                  
npm notice 3.1kB  plugins/mail_from.access.js                                    
npm notice 505B   plugins/mail_from.blocklist.js                                 
npm notice 7.0kB  plugins/mail_from.is_resolvable.js                             
npm notice 549B   plugins/mail_from.nobounces.js                                 
npm notice 155B   plugins/max_unrecognized_commands.js                           
npm notice 16.9kB plugins/messagesniffer.js                                      
npm notice 1.9kB  plugins/prevent_credential_leaks.js                            
npm notice 8.2kB  plugins/process_title.js                                       
npm notice 294B   plugins/profile.js                                             
npm notice 441B   plugins/queue/deliver.js                                       
npm notice 811B   plugins/queue/discard.js                                       
npm notice 1.1kB  plugins/queue/lmtp.js                                          
npm notice 3.0kB  plugins/queue/qmail-queue.js                                   
npm notice 4.9kB  plugins/queue/quarantine.js                                    
npm notice 2.7kB  plugins/queue/rabbitmq_amqplib.js                              
npm notice 6.2kB  plugins/queue/rabbitmq.js                                      
npm notice 1.2kB  plugins/queue/smtp_bridge.js                                   
npm notice 10.8kB plugins/queue/smtp_forward.js                                  
npm notice 3.8kB  plugins/queue/smtp_proxy.js                                    
npm notice 386B   plugins/queue/test.js                                          
npm notice 134B   plugins/rate_limit.js                                          
npm notice 3.1kB  plugins/rcpt_to.access.js                                      
npm notice 520B   plugins/rcpt_to.blocklist.js                                   
npm notice 2.3kB  plugins/rcpt_to.host_list_base.js                              
npm notice 1.9kB  plugins/rcpt_to.in_host_list.js                                
npm notice 134B   plugins/rcpt_to.ldap.js                                        
npm notice 772B   plugins/rcpt_to.max_count.js                                   
npm notice 182B   plugins/rcpt_to.qmail_deliverable.js                           
npm notice 1.1kB  plugins/rdns.regexp.js                                         
npm notice 490B   plugins/record_envelope_addresses.js                           
npm notice 3.4kB  plugins/relay_acl.js                                           
npm notice 417B   plugins/relay_all.js                                           
npm notice 914B   plugins/relay_force_routing.js                                 
npm notice 6.6kB  plugins/relay.js                                               
npm notice 217B   plugins/reseed_rng.js                                          
npm notice 12.2kB plugins/spamassassin.js                                        
npm notice 10.8kB plugins/spf.js                                                 
npm notice 999B   plugins/tarpit.js                                              
npm notice 4.7kB  plugins/tls.js                                                 
npm notice 1.2kB  plugins/toobusy.js                                             
npm notice 4.5kB  plugins/xclient.js                                             
npm notice 185B   tests/.eslintrc.yaml                                           
npm notice 47B    tests/config/auth_flat_file.ini                                
npm notice 424B   tests/config/dhparams.pem                                      
npm notice 46B    tests/config/host_list                                         
npm notice 21B    tests/config/outbound_tls_cert.pem                             
npm notice 20B    tests/config/outbound_tls_key.pem                              
npm notice 70B    tests/config/plugins                                           
npm notice 624B   tests/config/smtp_forward.ini                                  
npm notice 86B    tests/config/smtp.ini                                          
npm notice 1.2kB  tests/config/tls_cert.pem                                      
npm notice 1.7kB  tests/config/tls_key.pem                                       
npm notice 908B   tests/config/tls.ini                                           
npm notice 2.7kB  tests/config/tls/goobered.pem                                  
npm notice 3.1kB  tests/config/tls/haraka.local.pem                              
npm notice 2.9kB  tests/config/tls/mismatched.pem                                
npm notice 10.5kB tests/connection.js                                            
npm notice 501B   tests/fixtures/line_socket.js                                  
npm notice 4.2kB  tests/fixtures/todo_qfile.txt                                  
npm notice 5.1kB  tests/fixtures/util_hmailitem.js                               
npm notice 1.8kB  tests/fixtures/vm_harness.js                                   
npm notice 5.8kB  tests/host_pool.js                                             
npm notice 13B    tests/installation/config/test-plugin-flat                     
npm notice 62B    tests/installation/config/test-plugin.ini                      
npm notice 13B    tests/installation/config/tls.ini                              
npm notice 75B    tests/installation/plugins/base_plugin.js                      
npm notice 50B    tests/installation/plugins/folder_plugin/index.js              
npm notice 227B   tests/installation/plugins/folder_plugin/package.json          
npm notice 176B   tests/installation/plugins/inherits.js                         
npm notice 65B    tests/installation/plugins/load_first.js                       
npm notice 36B    tests/installation/plugins/plugin.js                           
npm notice 67B    tests/installation/plugins/tls.js                              
npm notice 9.6kB  tests/logger.js                                                
npm notice 676B   tests/mail_specimen/base64-root-part.txt                       
npm notice 18.8kB tests/mail_specimen/varied-fold-lengths-preserve-data.txt      
npm notice 9.5kB  tests/mailbody.js                                              
npm notice 3.1kB  tests/mailheader.js                                            
npm notice 838B   tests/messagestream.js                                         
npm notice 7.6kB  tests/outbound_bounce_net_errors.js                            
npm notice 15.6kB tests/outbound_bounce_rfc3464.js                               
npm notice 3.5kB  tests/outbound/hmail.js                                        
npm notice 10.6kB tests/outbound/index.js                                        
npm notice 1.9kB  tests/outbound/qfile.js                                        
npm notice 7.9kB  tests/plugins.js                                               
npm notice 14.7kB tests/plugins/aliases.js                                       
npm notice 16.9kB tests/plugins/auth/auth_base.js                                
npm notice 2.7kB  tests/plugins/auth/auth_vpopmaild.js                           
npm notice 11.3kB tests/plugins/bounce.js                                        
npm notice 8.3kB  tests/plugins/clamd.js                                         
npm notice 13.2kB tests/plugins/data.headers.js                                  
npm notice 5.1kB  tests/plugins/deprecated/relay_acl.js                          
npm notice 1.8kB  tests/plugins/deprecated/relay_all.js                          
npm notice 7.0kB  tests/plugins/dkim_sign.js                                     
npm notice 7.4kB  tests/plugins/dns_list_base.js                                 
npm notice 2.9kB  tests/plugins/dnsbl.js                                         
npm notice 3.6kB  tests/plugins/early_talker.js                                  
npm notice 1.9kB  tests/plugins/greylist.js                                      
npm notice 21.9kB tests/plugins/helo.checks.js                                   
npm notice 5.6kB  tests/plugins/mail_from.is_resolvable.js                       
npm notice 6.6kB  tests/plugins/queue/smtp_forward.js                            
npm notice 4.8kB  tests/plugins/rcpt_to.host_list_base.js                        
npm notice 7.9kB  tests/plugins/rcpt_to.in_host_list.js                          
npm notice 11.6kB tests/plugins/relay.js                                         
npm notice 5.8kB  tests/plugins/spamassassin.js                                  
npm notice 8.5kB  tests/plugins/spf.js                                           
npm notice 2.5kB  tests/plugins/tls.js                                           
npm notice 1.3MB  tests/queue/1507509981169_1507509981169_0_61403_e0Y0Ym_1_fixed 
npm notice 1.3MB  tests/queue/1507509981169_1507509981169_0_61403_e0Y0Ym_1_haraka
npm notice 2.5kB  tests/queue/1508269674999_1508269674999_0_34002_socVUF_1_haraka
npm notice 4.0kB  tests/queue/1508455115683_1508455115683_0_90253_9Q4o4V_1_haraka
npm notice 2.2kB  tests/rfc1869.js                                               
npm notice 14.9kB tests/server.js                                                
npm notice 2.1kB  tests/smtp_client.js                                           
npm notice 3.5kB  tests/smtp_client/auth.js                                      
npm notice 3.3kB  tests/smtp_client/basic.js                                     
npm notice 1.9kB  tests/spf.js                                                   
npm notice 4.2kB  tests/test-queue/delete-me                                     
npm notice 9.3kB  tests/tls_socket.js                                            
npm notice 5.7kB  tests/transaction.js                                           
npm notice === Tarball Details === 
npm notice name:          Haraka                                  
npm notice version:       2.8.22                                  
npm notice package size:  2.2 MB                                  
npm notice unpacked size: 3.9 MB                                  
npm notice shasum:        204d69aec39bda496cd47c7375f3e4b5389b02ec
npm notice integrity:     sha512-z1OEajlPro9h8[...]0pnDKGflqofxQ==
npm notice total files:   351                                     
npm notice 
+ Haraka@2.8.22
````

**Comment by baudehlo** [comment]
Thanks Matt.

**Pull request merged**
