### PR TITLE
Release v2.8.9

### PR DESCRIPTION
**Pull request by baudehlo**
Checklist:

- [x] Start a N-week quiet period
- [x] Update [haraka-tld](https://github.com/haraka/haraka-tld)
- [x] Draft a release on the [releases page](https://github.com/haraka/Haraka/releases) (Save draft)
- Create a PR with:
    - [x] Updated [Changes](Changes)
    - [x] Bumped version in [package.json](https://github.com/haraka/Haraka/blob/master/package.json)
    - ~~Updated dependencies identified with `grunt versioncheck`~~
- ~~For major version releases:~~
- [x] Update release date in [Changes](https://github.com/haraka/Haraka/blob/master/Changes)
- [x] ~~`git tag v<release_number>; git push --tags`~~ - done by publishing the release
- [x] `npm publish`
- [x] Post `Changes` file on the draft release and publish the release 
- [x] update [haraka's wikipedia page](https://en.wikipedia.org/wiki/Haraka_(software))
- [ ] Email the mailing list
- [ ] Publish a blog post
- [ ] Edit the /topic on #haraka IRC channel

### CODE REVIEW

**Comment by baudehlo** [comment]
I think we're ready to release. Can I get some +1's @msimerson @smfreegard ?

**Comment by baudehlo** [comment]
Actually there's still a pending issue (only documented on IRC) from @darkpixel - I'd like time to see if I can replicate/fix that before release.

**Comment by darkpixel** [comment]
I don't know @baudehlo...it might hold up the release for a while trying to dig to the bottom of it, and it's been around for at least ~90 days worth of releases.  And it's entirely possible it's something specific to my site and the Barracuda...

**Comment by baudehlo** [comment]
Well there's a lot of Barracuda boxes out there and we need to work with
everything. So don't worry about it - we need to fix it.

**Comment by msimerson** [comment]
The only known issue I'm aware of is that Haraka will not run on node V6 with the syslog plugin. The upstream repo has a fix for modern-syslog but hasn't cut a new release yet.

**Comment by msimerson** [comment]
+1

**Comment by baudehlo** [comment]
I feel like I'm getting closer on the outbound issue. Give me another week.

**Comment by msimerson** [comment]
I've seen related activity. How are you feeling now @baudehlo ?

**Comment by baudehlo** [comment]
Ready to rock. I was going to do it this weekend but if you have time today that's cool too. Note this release has a security vulnerability fix that needs to go into the release notes.

**Comment by msimerson** [comment]
Oops. I did this:

````
$ npm publish
+ Haraka@2.8.9
````

before re-reading and remembering this:

> this release has a security vulnerability fix that needs to go into the release notes.

**Comment by msimerson** [comment]
Already, I'm going to leave updating the release notes and the last few items in the checklist to @baudehlo. I've got my own servers updated to 2.8.8 recently, so I should be able to quickly and easily to test deployments against HEAD. I feel better about rolling releases after I've been able to deploy them and watch 'em not break for a while.

**Pull request merged**
