### PR TITLE
define WRITE_EXCL

### LINKED ISSUE #2008: Crash "WRITE_EXCL is not defined"
### system info

Using haraka 4e59e3a909986a928e2010b6af73fec1f62dfca3.

### Steps to reproduce

Not sure how to reproduce but we got the following backtrace:
```
Jul 21 08:38:33 domain.com dockerd[1377]: [CRIT] [-] [core] ReferenceError: WRITE_EXCL is not defined
Jul 21 08:38:33 domain.com dockerd[1377]: [CRIT] [-] [core]     at split_to_new_recipients (/app/haraka/outbound/hmail.js:1278:54)
Jul 21 08:38:33 domain.com dockerd[1377]: [CRIT] [-] [core]     at finish_processing_mail (/app/haraka/outbound/hmail.js:594:13)
Jul 21 08:38:33 domain.com dockerd[1377]: [CRIT] [-] [core]     at pluggableStream.<anonymous> (/app/haraka/outbound/hmail.js:833:29)
Jul 21 08:38:33 domain.com dockerd[1377]: [CRIT] [-] [core]     at emitOne (events.js:96:13)
Jul 21 08:38:33 domain.com dockerd[1377]: [CRIT] [-] [core]     at pluggableStream.emit (events.js:188:7)
Jul 21 08:38:33 domain.com dockerd[1377]: [CRIT] [-] [core]     at pluggableStream.socket.process_data (/app/haraka/line_socket.js:24:20)
Jul 21 08:38:33 domain.com dockerd[1377]: [CRIT] [-] [core]     at pluggableStream.<anonymous> (/app/haraka/line_socket.js:35:48)
Jul 21 08:38:33 domain.com dockerd[1377]: [CRIT] [-] [core]     at emitOne (events.js:96:13)
Jul 21 08:38:33 domain.com dockerd[1377]: [CRIT] [-] [core]     at pluggableStream.emit (events.js:188:7)
Jul 21 08:38:33 domain.com dockerd[1377]: [CRIT] [-] [core]     at Socket.<anonymous> (/app/haraka/tls_socket.js:54:14)
```

Upstream bug: https://git.cloudron.io/cloudron/box/issues/382

### PR DESCRIPTION
**Pull request by gramakri**
Fixes #2008

Changes proposed in this pull request:
- Define WRITE_EXCL like in outbound/index.js

Checklist:
- [ ] docs updated
- [ ] tests updated

### CODE REVIEW

**Comment by gramakri** [comment]
So, this fails only for node.js 6? I cannot make out from the logs what exactly is failing.

**Comment by gramakri** [comment]
@baudehlo I think this code came from 4ed67c548ef88dbb9915c4361e780a1a9d44b783. Can you review this?

**Comment by msimerson** [comment]
This change looks good to me. However, I wonder if we shouldn't pay a nod to [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) and put that into [haraka-constants](https://github.com/haraka/haraka-constants) instead?

**Comment by gramakri** [comment]
@msimerson Thanks :)

**Pull request closed without merging**
