### PR TITLE
Fixed swaks test command

### PR DESCRIPTION
**Pull request by dtruel**
The swaks test command in the tutorial for outbound email has the to and from addresses reversed.  I'm creating this pull request so nobody else wonders why their server is timing out trying to reach example.com's ip

Checklist:
- [x] docs updated

### CODE REVIEW

**Comment by msimerson** [comment]
Actually, both the -to and -from should be changed to real values. Maybe we should make that more obvious with something like this?

    swaks -to me@example.com -from me@example.com -s localhost \

**Comment by dtruel** [comment]
I agree, I think your solution is definitely more readable which is exactly what you want in a tutorial.  Aren't you supposed to do two dashed (`--to`) instead of one? I know it works with one but the Swaks manpages always use two dashes instead of one.

**Comment by msimerson** [comment]
Sounds great. Please update this PR accordingly and I'll merge it.

**Comment by msimerson** [comment]
thanks @dtruel

**Comment by dtruel** [comment]
Yup. Thanks for all your hard work maintaining this amazing repo.

**Pull request merged**
