### PR TITLE
haraka release 2.8.0

### LINKED ISSUE #1372: client.socket.remoteAddress undefined
related to #1361 

### Node.js version
Tested on v4 and v5

### Haraka version
`Starting up Haraka version 2.8.0-alpha.5`

Yes, alpha.5 (and later) **includes** the patch in PR #1362

### Expected behavior
not to crash.

### Observed behavior

````
[INFO] [-] [core] [smtp_client_pool] [25:127.0.0.6:300] dispense() clients=1 available=0
[CRIT] [-] [core] Error: ipaddr: the address has neither IPv6 nor IPv4 format
[CRIT] [-] [core]     at Object.ipaddr.parse (/usr/local/lib/node_modules/Haraka/node_modules/ipaddr.js/lib/ipaddr.js:438:13)
[CRIT] [-] [core]     at Object.ipaddr.process (/usr/local/lib/node_modules/Haraka/node_modules/ipaddr.js/lib/ipaddr.js:459:17)
[CRIT] [-] [core]     at pluggableStream.<anonymous> (/usr/local/lib/node_modules/Haraka/smtp_client.js:131:35)
[CRIT] [-] [core]     at emitTwo (events.js:87:13)
[CRIT] [-] [core]     at pluggableStream.emit (events.js:172:7)
[CRIT] [-] [core]     at Socket.<anonymous> (/usr/local/lib/node_modules/Haraka/tls_socket.js:51:14)
[CRIT] [-] [core]     at emitNone (events.js:72:20)
[CRIT] [-] [core]     at Socket.emit (events.js:166:7)
[CRIT] [-] [core]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1048:10)
````

### Steps to reproduce

* npm install Haraka@2.8.0-alpha.7
* enable smtp_forward plugin
* send an email (I used swaks)
* when it begins to forward the connection, the results above are thrown

### Temporary workaround

```diff
diff --git a/smtp_client.js b/smtp_client.js
index 0117758..a912cd5 100644
--- a/smtp_client.js
+++ b/smtp_client.js
@@ -128,7 +128,13 @@ function SMTPClient (port, host, connect_timeout, idle_timeout) {
     this.socket.on('connect', function () {
         // Remove connection timeout and set idle timeout
         client.socket.setTimeout(((idle_timeout) ? idle_timeout : 300) * 1000);
-        client.remote_ip = ipaddr.process(client.socket.remoteAddress).toString();
+        if (client.socket.remoteAddress) {
+            // "Value may be undefined if the socket is destroyed"
+            client.remote_ip = ipaddr.process(client.socket.remoteAddress).toString();
+        }
+        else {
+            logger.logerror('client.socket.remoteAddress undefined!');
+        }
     });
 
     var closed = function (msg) {
````

### PR DESCRIPTION
**Pull request by msimerson**
See included Changes.

# Calling all testers!

There are several SIGNIFICANT changes merged in this release. To make this easier to test, an alpha version has been published to npm. You must specify the version specifically to get it like this:

 `npm install -g  Haraka@2.8.0-alpha.4`

# Things to test carefully

* config loading. haraka -i no longer fully populates config/*, instead loading config settings from the npm install dir and then applying local overrides found in config/*. See #1341
* The public-suffix and config/tld-* files have been removed to haraka/haraka-tld. It Works For Me but broader testing is welcome.
* Outbound TLS and `queue/smtp_*` plugins now honor tls.ini. This needs broader testing.

# Known Issues / TODO
1. [x] config/plugins not installed (#1360)
2. [x] config/dkim/dkim_gen_key.sh not installed
3. [x] merge #1355
4. [x] merge #1357
5. [x] merge #1359
6. [ ] fix #1372 (see bandaid in #1397)

# Checklist

1. [x] Publish alpha/beta 
1. [x] Start a N-week quiet period
1. [x] Update [Changes](Changes)
1. [x] Update [haraka-tld](https://github.com/haraka/haraka-tld)
1. [x] For major version releases:
1. [x] Bump version in [package.json](https://github.com/haraka/Haraka/blob/master/package.json)
1. [x] Check if any dependencies should be updated with `grunt versioncheck`
1. [ ] Update release date in [Changes](https://github.com/haraka/Haraka/blob/master/Changes)
1. [ ] git tag v<release_number>; git push --tags
1. [ ] npm publish
1. [ ] update [haraka's wikipedia page](https://en.wikipedia.org/wiki/Haraka_(software))
1. [ ] Email the mailing list
1. [ ] Publish a blog post

### CODE REVIEW

**Comment by msimerson** [comment]
depends on #1355

**Comment by baudehlo** [comment]
Should also depend on #1340

I have a couple more features that need added to that.

**Comment by msimerson** [comment]
> I have a couple more features that need added to that.

Since #1340 has been merged, maybe create a new Issue and depend on that?

Also, it's much easier for code reviewers to see where you are (and not have to read through the discussion every time they troll through the open PRs) if you put a checklist in the description at the top. The coolest part about the checklist is that it shows up in list view, so reviewers don't even have to open the PR to see if its ready.

# Checklist
- [ ] item one
- [ ] item two

**Comment by msimerson** [comment]
I just released [haraka-tld](https://github.com/haraka/haraka-tld) v1.0.4 which addresses an issue I discovered while testing 2.8.0.

**Comment by baudehlo** [comment]
Creating a new PR for that Inbound/Outbound having separate Ciphers.

**Comment by msimerson** [comment]
````
$ npm publish
+ Haraka@2.8.0-alpha.3
````

**Comment by msimerson** [comment]
Depends on #1359

**Comment by baudehlo** [comment]
What's funny is this is what I always thought 3.0 should be, rather than the major sweeping changes actually proposed in the 3.0 tag ;)

**Comment by msimerson** [comment]
> this is what I always thought 3.0 should be

When I think "semver major" I think, "breaking API changes."  Part of waiting so long to get some of this stuff done is that we've wanted it done for so long that we've thought about and found ways to git-er-done without breaking APIs.

Funnier still would be all the 3.0-pegged stuff landing in 2.NN and the only thing that changed in 3.0.0 is dropping node 0.10/12 support.

**Comment by baudehlo** [comment]
I agree to the extent that I think semver is the be-all-end-all of version numbering. Sometimes you just want a big number bump to tell people "hey this is a big change to how we were doing things - here be dragons".

**Comment by msimerson** [comment]
$ npm publish
+ Haraka@2.8.0-alpha.4

**Comment by baudehlo** [comment]
config/plugins fixed in #1360

**Comment by msimerson** [comment]
```sh
$ npm publish
+ Haraka@2.8.0-alpha.6
```

**Comment by msimerson** [comment]
````
$ npm publish
+ Haraka@2.8.0-alpha.7
````

**Comment by msimerson** [comment]
$ npm publish
+ Haraka@2.8.0-alpha.8

**Comment by baudehlo** [comment]
Where are we at with #1372 ?

**Comment by msimerson** [comment]
A bandaid was merged that prevents the crash, but the problem is not "solved" yet. I started looking but haven't had time to investigate far enough.

**Comment by msimerson** [comment]
$ npm publish
+ Haraka@2.8.0-alpha.9

**Comment by baudehlo** [comment]
Time for a new alpha @msimerson ?

**Comment by baudehlo** [comment]
(or perhaps even Beta now - we are very close)

**Comment by msimerson** [comment]
Yeah, I think a beta release is in order.

**Comment by msimerson** [comment]
````
$ npm publish
+ Haraka@2.8.0-beta.1
````

**Comment by baudehlo** [comment]
Remaining issues that seem worth fixing:

#1387
#1411 (PR issued)
#1386 (I'm going to look into that this weekend or tonight)
#1381 - seems like an easy fix @Dexus you said you were on this?

**Comment by Dexus** [comment]
Yes i'm already finished it but not yet had the time to push. Current in a project outside.

**Comment by baudehlo** [comment]
1386 and 1411 are now fixed.

@smfreegard did you have any thoughts on #1387?

**Comment by BradRuderman** [comment]
@baudehlo  I don't think its worth fixing, I think outbound.js and smtp_forward should be modified to use a standard underlying smtp client. The main difference is synchronous vs not-synchronous.

**Comment by smfreegard** [comment]
@BradRuderman  - They're both async, there's no non-async code there.

@baudehlo - the problem is this: https://github.com/haraka/Haraka/blob/master/plugins/queue/smtp_forward.js#L69

It's using the wrong event handler to sent the AUTH command - it's attempting AUTH on 'greeting' when it should be using on('capabilities') instead: https://github.com/haraka/Haraka/blob/master/smtp_client.js#L395

Should be an easy fix, but I can't test it here easily.

**Comment by BradRuderman** [comment]
@smfreegard  Right you have 2 that have the same purpose in different methods. I think it would be a better maintenance to have 1 common library.

I implemented smtp_forward using outbound.js, when I mean "Async" my implementation doesn't pass down upstream errors back to the client using outbound.js. It does using smtp_forward.

**Comment by baudehlo** [comment]
OK I PR'd a fix for #1387 - But as you say, it's hard to test, so I haven't added any tests for it.

**Comment by Dexus** [comment]
PR #1437 fix #1381

**Comment by baudehlo** [comment]
OK I think we're done, unless someone can research/fix #1372 

Beta or release?

**Comment by smfreegard** [comment]
I think we need to wait.  There's a report on IRC of broken attachments using smtp_proxy that looks legit.  I'm just waiting for more details.

**Comment by msimerson** [comment]
I'll publish another beta in a day or two.

As far as waiting, I err on not letting perfect get in the way of good enough. 2.8.0 will be a .0 release, which anyone that knows anything about software will know, will have bugs. We'll have plenty more version numbers after .0 to work out the issues.

**Comment by baudehlo** [comment]
No need to wait. I fixed it. I'd rather just release 2.8.0 now.

**Comment by msimerson** [comment]
> I'd rather just release 2.8.0 now.

+1. I say go for it. The checklist of things to do is above. If not, I may get time later tonight when I come back inside.

**Comment by gramakri** [comment]
FWIW, I have been testing with master for a couple of weeks now. The main reason I moved to master was because of the minimal config change. Previously, we had all the config files and it was very hard to track what was actually changed (and what config files to inspect between releases). With master, I only have the config files that I changed.

So far, it seems to work perfectly. Thanks!

**Comment by msimerson** [comment]
````
$ npm publish
+ Haraka@2.8.0
````

**Comment by baudehlo** [comment]
:applause:

**Comment by smfreegard** [comment]
Well done everyone!

**Comment by Dexus** [comment]
:clap:

**Comment by msimerson** [comment]
FYI: I didn't catch up the Changes file with the past couple weeks commits, nor update the release date. This is a reminder to do that.

**Pull request merged**
