### PR TITLE
Merge master into v3devel

### PR DESCRIPTION
**Pull request by Dexus**

### CODE REVIEW

**Comment by baudehlo** [comment]
I'm happy to merge this, but this branch seems almost redundant right now. Thoughts?

**Comment by Dexus** [comment]
Yeah the most is redundant, the graylisting plugin can i also merge into the master or I create a own external plugin for it. What your Thoughts?

**Comment by baudehlo** [comment]
Is that different to our current plugins/greylist.js ?

**Comment by Dexus** [comment]
The current greylist is only in v3devel a other is not in master if i'm correct remember. And i would build it as a external plugin for optional install.

Von meinem iPhone gesendet

**Comment by baudehlo** [comment]
https://github.com/haraka/Haraka/blob/master/plugins/greylist.js ?

**Comment by Dexus** [comment]
Ah yes that is the plugin, okay than we can delete v3devel.

Von meinem iPhone gesendet

**Comment by baudehlo** [comment]
Closing.

**Pull request closed without merging**
