### PR TITLE
Load plugin config from own folder and merge

### PR DESCRIPTION
**Pull request by baudehlo**
Let me know what you think of these changes.

### CODE REVIEW

**Comment by baudehlo** [comment]
Tests added. Code fixed. Pretty much ready for this to be peer reviewed.

One weakness is if the plugin does `require('./config')` and uses that.

We can probably fix that, because that version of `require()` is already shimmed. What do people think?

**Comment by baudehlo** [comment]
Added docs.

**Comment by baudehlo** [comment]
Made require(`./config`) work the same as plugin.config does.

**Comment by baudehlo** [comment]
Objections to merging this so we can all start playing with it?

**Comment by smfreegard** [comment]
+1 - Can't see anything obviously wrong.  Sweet solution!

**Comment by Dexus** [comment]
:+1: looks good to me. 

> Sweet solution!
Agree :)

**Pull request merged**
