### PR TITLE
haraka/Haraka#1099 use TLSSocket instead of createSecurePair

### PR DESCRIPTION
**Pull request by typingArtist**
While this change looks like cosmetics, it is needed for advanced TLSSocket operations like OCSP Stapling. This also fixes long-lasting #1099.

Checklist:
- [x] no need for updating the docs
- [x] no need for updating tests

### CODE REVIEW

**Comment by msimerson** [comment]
While I'm really happy to see that crusty old tls_socket get some love, it might be better to just jettison that sucker. See #1099  (we can do that now b/c we recently dropped support for node 0.10).

**Comment by typingArtist** [comment]
My aim was just to make it work with TLSSocket for allowing me to add OCSP Stapling functionality (see #1673).

If you don’t mind, I leave the refactoring to you.

**Comment by smfreegard** [comment]
Why did you only change the server end to use TLSSocket and ignore the client?   Surely supporting OSCP stapling in both is desirable?

**Comment by typingArtist** [comment]
Definitely it is. I just started with the one end I expected to be more work.

**Comment by smfreegard** [comment]
Ok - no great.  Nice work on this.  I've wanted to support SMTP STS or DANE in Haraka for a while now, but it's reliant of Node getting support for DNSSEC and TLSA record types etc.

**Pull request merged**
