### PR TITLE
add smtp bridge

### PR DESCRIPTION
**Pull request by jesucarr**

### CODE REVIEW

**Comment by baudehlo** [comment]
Needs docs.

**Comment by jesucarr** [comment]
docs added

**Comment by msimerson** [comment]
The docs are good, thanks!

They make me think they should include a section that explains how smtp_bridge and smtp_proxy work, how they differ, and suggestions for users on how to pick the appropriate one.

**Comment by msimerson** [comment]
Also, you've got some lint issues preventing the test suite from passing:

````
/home/travis/build/haraka/Haraka/plugins/auth/auth_bridge.js
  20:2  error  Expected indentation of 4 space characters but found 0  indent
/home/travis/build/haraka/Haraka/plugins/queue/smtp_bridge.js
   1:28  error  Trailing spaces not allowed  no-trailing-spaces
  27:6   error  Trailing spaces not allowed  no-trailing-spaces
✖ 3 problems (3 errors, 0 warnings)
````

**Comment by baudehlo** [comment]
Any chance we can turn off no-trailing-spaces? I mean it's fine on the end
of a line with text there, but on a blank line it's super annoying.

**Comment by jesucarr** [comment]
Sorry what blank line?

**Comment by msimerson** [comment]
> Any chance we can turn off no-trailing-spaces? 

@jesucarr , he's talking about our lint checks, that require trailing whitespace to be removed. 

@baudehlo, I'd rather add a FAQ with instructions for configuring $EDITOR to automatically trim trailing whitespace. Most programming editors either do it automatically or can be easily configured to.

**Comment by baudehlo** [comment]
Oh I was talking to msimerson about the settings we use for lint. We block
when there are spaces to the current indent level on blank lines. It's
really annoying as that's the default behaviour for sublimetext.

**Comment by msimerson** [comment]
@baudehlo, see https://packagecontrol.io/packages/TrailingSpaces https://github.com/SublimeText/TrailingSpaces.  It's a very popular plugin for SublimeText. :)

**Comment by baudehlo** [comment]
Sublime settings are global or per-project, so I'd have to create a whole
"project" for Haraka. Currently I just type "subl ." and open the whole
folder - it'd be rather annoying to have to create a project, but I guess
it can be done - I can't do it globally as other projects don't have the
same rules. It's just a big change in my workflow to open a "project" vs a
folder.

**Comment by msimerson** [comment]
> I can't do it globally as other projects don't have the same rules.

\<mind blown\>You have a project that **requires** trailing spaces this would conflict with?\</mind\>

Now that I go rummaging through Package Control, I see that TrailingSpaces isn't the plugin I used after all (not even installed locally). What I have instead is:

* https://packagecontrol.io/packages/JSCS-Formatter
* https://packagecontrol.io/packages/JsFormat
* http://www.sublimelinter.com/en/latest/

Example: I'm in a text block indented one level and hit return. I get a newly indented line. I hit return again, leaving a blank line and begin typing. The indent spaces in the previous line are automatically removed. Which plugin is doing that for me?

IIRC, I toyed with JSCS before ditching the "jshint + JSCS" combo in favor of eslint, so I *think* JsFormat is the plugin I'm using that automatically avoids trailing whitespace for me. If I do leave some in, then the SublimeLinter-eslint plugin highlights it right away, as it knows the rules for whichever repo I happened to type `subl .` in.

**Comment by baudehlo** [comment]
On Thu, Feb 4, 2016 at 4:40 PM, Matt Simerson <notifications@github.com>
wrote:

> <mind blown>You have a project that *requires* trailing spaces this would
> conflict with?</mind>
>
>
No you're confused. If I enable the setting, every time I edit another
project (e.g. work) it's going to give me a massive irrelevant diff.

**Comment by msimerson** [comment]
I think perhaps you're confused. None of those plugins are going to **automatically** remove existing trailing spaces. They prevent you from inadvertently adding new ones. The TrailingSpaces plugin *can* remove them all, but it requires you to click a menu option.

**Comment by jesucarr** [comment]
@msimerson you don't need a plugin for Sublime to remove trailing whitespace, simply add to your user settings `"trim_trailing_white_space_on_save": true,`.

**Comment by msimerson** [comment]
Ahhh, but you see @jesucarr, using `trim_trailing_white_space_on_save": true` would create exactly the problem that @baudehlo  is worried about, "a massive irrelevant diff" every time he edits a $work file.

**Comment by baudehlo** [comment]
What I want is a "trim trailing spaces" option that does it only if there's
text on the line :) I'd be fine with using that in current projects.

I'll look into the plugins, but I still think the lint setting should only
care about the case above. Who cares if there's whitespace on a blank line?

**Comment by msimerson** [comment]
Merged, thanks @jesucarr

**Pull request closed without merging**
