### PR TITLE
Get local_ip from getsockname() instead of server properties

### LINKED ISSUE #2914: connection.local_ip returns bind address instead of actual IP
**Describe the bug**
`local_ip` returns the address the socket is bound to (which is in `listen`), instead of the IP address that actually received the connection. 

**Expected behavior**
`local_ip` provides the local IP address to which the connection was made.

**Observed behavior**
`local_ip` is `::`.

**System Info:**

Haraka | Haraka.js — Version: 2.8.27
 --- | :--- 
Node | v12.20.1
OS | Linux censored 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
openssl | OpenSSL 1.1.1d  10 Sep 2019

### PR DESCRIPTION
**Pull request by Juerd**
Fixes #2914

In the case of binding to a specific existing address, client.localAddress
should be the same as the bind address and this commit doesn't change that.

In the case of binding to a non-existing address, no client will exist until
the address does exist, and this commit doesn't change that.

Finally, in the case of binding to INADDR_ANY, the bind address is useless
information (that is: I can't think of any use case where this fact would be
useful during handling an incoming connection), and this commit changes the
value from :: or 0.0.0.0 to a value that is actually useful: the IP address on
which the incoming connection was actually accepted.

Checklist:
- [ ] docs updated ← N/A
- [X] tests updated
- [X] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

### CODE REVIEW

**Review by msimerson — APPROVED** [review]

**Review by msimerson — APPROVED** [review]

**Comment by msimerson** [comment]
Indeed, this changes the log entries on my mail server for new connections:

### before

`[core] connect ip=204.11.99.6 port=51872 local_ip=:: local_port=465`

### after

`[core] connect ip=204.11.99.6 port=63511 local_ip=172.16.15.9 local_port=465`

For those that bind their MTA to a public IP (ie, not behind a firewall / NAT / haproxy), I suppose this change has some value.

**Comment by msimerson** [comment]
Oops, I merged that too soon. After applying the changes to connection, sometimes I get this:

````
Jan 24 20:16:06 haraka haraka[51798]: [CRIT] [-] [core] Error: ipaddr: the address has neither IPv6 nor IPv4 format
Jan 24 20:16:06 haraka haraka[51798]: [CRIT] [-] [core]     at Object.ipaddr.parse (/root/Haraka/node_modules/ipaddr.js/lib/ipaddr.js:863:19)
Jan 24 20:16:06 haraka haraka[51798]: [CRIT] [-] [core]     at new Connection (/root/Haraka/connection.js:138:20)
Jan 24 20:16:06 haraka haraka[51798]: [CRIT] [-] [core]     at Function.setupClient (/root/Haraka/connection.js:151:44)
Jan 24 20:16:06 haraka haraka[51798]: [CRIT] [-] [core]     at onConnect (/root/Haraka/server.js:364:33)
Jan 24 20:16:06 haraka haraka[51798]: [CRIT] [-] [core]     at Object.exports.createConnection (/root/Haraka/connection.js:1924:12)
Jan 24 20:16:06 haraka haraka[51798]: [CRIT] [-] [core]     at Server.<anonymous> (/root/Haraka/tls_socket.js:688:9)
Jan 24 20:16:06 haraka haraka[51798]: [CRIT] [-] [core]     at Object.ipaddr.process (/root/Haraka/node_modules/ipaddr.js/lib/ipaddr.js:883:27)
Jan 24 20:16:06 haraka haraka[51798]: [CRIT] [-] [core]     at Server.emit (events.js:314:20)
Jan 24 20:16:06 haraka haraka[51798]: [CRIT] [-] [core]     at Object.onconnection (net.js:1558:8)
Jan 24 20:16:06 haraka haraka[51798]: [CRIT] [-] [core]     at onconnection (internal/cluster/child.js:189:12)
Jan 24 20:16:06 haraka haraka[51798]: [NOTICE] [-] [core] Shutting down
Jan 24 20:16:06 haraka haraka[51764]: [NOTICE] [-] [core] worker 3 exited with error code: 1
````

**Comment by Juerd** [comment]
That's interesting; I have not encountered that.

**Comment by msimerson** [comment]
> That's interesting; I have not encountered that.

If you had, and didn't note it on the PR, I'd give you a good dutch rub. 🤪

I logged a few values of `self.client.localAddress` to see what might be behind it.

````
::ffff:172.16.15.9
undefined
undefined
undefined
::ffff:172.16.15.9
````

**Comment by Juerd** [comment]
A few possibilities come to mind:
- `self.client.targetsocket` is not an IP socket (but Haraka doesn't support unix sockets, or does it?)
- `getsockname` system call fails
- - I've looked up some man pages for getsockname for different OSes. Apparently, under FreeBSD it can fail if the connection has been reset by peer (silly feature). That's unlikely during the socket initialization in net.js, but not impossible. Do you happen to use FreeBSD?
- multiple processes, where one for whatever is using the previous version of `tls_socket.js`

**Comment by msimerson** [comment]
> Do you happen to use FreeBSD?

I do.

**Comment by msimerson** [comment]
> multiple processes, where one for whatever is using the previous version of tls_socket.js

That's possible too. I'm running multiple processes and do get these messages in my logs: `[core] client requested TLS resumeSession`

**Comment by Juerd** [comment]
If you wrap the new localAddress part in a `try` block with same additional logging, does it look like these sockets are indeed dead on arrival?

**Comment by msimerson** [comment]
For now I've just done this:

```js
self.set('local', 'ip', ipaddr.process(self.client.localAddress || local_addr.address).toString());
self.set('local', 'port', (self.client.localPort || local_addr.port));
```

and that avoids calling `undefined.toString()` and crashing the process.

> If you wrap the new localAddress part in a try block with some additional logging, does it look like these sockets are indeed dead on arrival?

I'm not sure exactly what you're asking me to log. Perhaps a diff would make it clear.

**Comment by Juerd** [comment]
> For now I've just done this:
> 
> ```js
> self.set('local', 'ip', ipaddr.process(self.client.localAddress || local_addr.address).toString());
> self.set('local', 'port', (self.client.localPort || local_addr.port));
> ```
> 
> and that avoids calling `undefined.toString()` and crashing the process.

Good idea.

> > If you wrap the new localAddress part in a try block with some additional logging, does it look like these sockets are indeed dead on arrival?
> I'm not sure exactly what you're asking me to log. Perhaps a diff would make it clear.

Oh, just `try { set local ip and port } catch(e) { logger.logdebug("MARKER") }` to see if the failing sockets produce anything useful later on, or if every occurrence of `MARKER` goes along with other errors.

Or, with your latest changes, `if (self.client.localAddress === undefined) { logger.logdebug("MARKER") }`.

Although your change with the `||`s is probably good enough in practice.

**Comment by msimerson** [comment]
I don't understand what logging 'MARKER' is going to tell us. They connections aren't dead, they are quite normal connections. Here is one:

````
[INFO] [core] undefined
[INFO] [core] undefined
[NOTICE] [core] connect ip=204.11.99.6 port=60692 local_ip=:: local_port=25
[INFO] [karma] score: 0, good: 239641, bad: 593558, connections: 833436, history: -353917
[INFO] [p0f] os="FreeBSD 9.x or newer" link_type="Ethernet or modem" distance=8 total_conn=3752 shared_ip=Y
[INFO] [fcrdns] ip=204.11.99.6  rdns="cali.tnpi.net" rdns_len=1 fcrdns="cali.tnpi.net" fcrdns_len=1 other_ips_len=0 invalid_tlds=0 generic_rdns=true
[INFO] [dnsbl] 
[INFO] [asn] asn: 63442, org: ServerFarm Realty, asn_score: -112583, asn_connections: 262589, asn_good: 74916, asn_bad: 187499, fail:asn:history
[INFO] [geoip] NA, US, 556km
[INFO] [helo.checks] helo_host: nagios.tnpi.net, ips: 204.11.99.6,173.45.131.6,2605:7900:20:a::6, pass:match_re, bare_ip, dynamic, big_co(not), valid_hostname, rdns_match(org_dom), forward_dns, host_mismatch
[INFO] [spf] identity=helo ip=204.11.99.6 domain="nagios.tnpi.net" mfrom=<postmaster@nagios.tnpi.net> result=None
[INFO] [spf] scope: helo, result: None, domain: nagios.tnpi.net
[INFO] [tls] secured: cipher=ECDHE-RSA-AES256-GCM-SHA384 version=TLSv1.2 verified=false
[INFO] [core]  hook=unrecognized_command plugin=tls function=upgrade_connection params=STARTTLS retval=OK msg=""
[INFO] [helo.checks] helo_host: nagios.tnpi.net, ips: 204.11.99.6,173.45.131.6,2605:7900:20:a::6, pass:match_re, bare_ip, dynamic, big_co(not), valid_hostname, rdns_match(org_dom), forward_dns, host_mismatch, host_mismatch
[INFO] [karma] score: -1, good: 239641, bad: 593558, connections: 833436, history: -353917, awards: 004,005,131
[NOTICE] [core] disconnect ip=204.11.99.6 rdns=cali.tnpi.net helo=nagios.tnpi.net relay=N early=N esmtp=Y tls=Y pipe=N errors=0 txns=0 rcpts=0/0/0 msgs=0/0/0 bytes=0 lr="" time=13.722
````

**Comment by Juerd** [comment]
The MARKER is just an identifier to see which connections have this issue. If those `undefined`s that you have are the value of `.localAddress` they can serve the same purpose, as can the `local_ip=::`.

But if they're normal connections, that means at least it's not the `getsockname` failing with ECONNRESET (FreeBSD) or ENOTCONN (NetBSD).

**Pull request merged**
