### PR TITLE
don't send RSET to LMTP

### PR DESCRIPTION
**Pull request by analogic**
I've experienced "Error: We are already running hooks! Fatal error!" and "Shuting down" due haraka sending "RSET" to dovecot with specialy formatted email. It also causes infinity delivery if haraka is autorestarted (cluster maybe affected too).

```
[INFO] [-] [core] [outbound] acquired socket D954D55A-11AB-4AE4-A3EF-39ABC7550010 for outbound::24:127.0.0.1:undefined:50
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] S: 220 mail.server Dovecot ready.\r\n
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] C: LHLO mail.server
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] S: 250-mail.server\r\n
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] S: 250-8BITMIME\r\n
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] S: 250-ENHANCEDSTATUSCODES\r\n
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] S: 250 PIPELINING\r\n
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] C: MAIL FROM:<root@bdd6a10d8c79>
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] S: 250 2.1.0 OK\r\n
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] C: RCPT TO:<root@server>
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] S: 250 2.1.5 OK\r\n
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] C: DATA
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] S: 354 OK\r\n
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] C: .
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] S: 250 2.0.0 <root@server> MOFlAVh73FuiHAAAaI4zhw Saved\r\n
[NOTICE] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound]  delivered file=1541175254725_1541175254725_0_4704_ppr5YZ_4_bdd6a10d8c79 domain=server host=127.0.0.1 ip=127.0.0.1 port=24 mode=LMTP tls=N auth=N response="<root@server> MOFlAVh73FuiHAAAaI4zhw Saved" delay=897.319 fails=0 rcpts=1/0/0
[DEBUG] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] running delivered hooks
[DEBUG] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] running delivered hook in stats plugin
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] C: RSET
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] S: 502 5.5.2 Unknown command\r\n
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] C: RSET
[INFO] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] bouncing mail: 502 5.5.2 Unknown command
[DEBUG] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] running bounce hooks
[DEBUG] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] running bounce hook in stats plugin
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] S: 502 5.5.2 Unknown command\r\n
[PROTOCOL] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] C: RSET
[INFO] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] bouncing mail: 502 5.5.2 Unknown command
[DEBUG] [20991B81-A096-4459-8C12-E0302D9A4DD1.1.1] [outbound] running bounce hooks
[CRIT] [-] [core] Error: We are already running hooks! Fatal error!
[CRIT] [-] [core]     at Object.plugins.run_hooks (/usr/lib/node_modules/Haraka/plugins.js:404:15)
[CRIT] [-] [core]     at HMailItem._bounce (/usr/lib/node_modules/Haraka/outbound/hmail.js:1217:17)
[CRIT] [-] [core]     at HMailItem.bounce (/usr/lib/node_modules/Haraka/outbound/hmail.js:1206:14)
[CRIT] [-] [core]     at pluggableStream.<anonymous> (/usr/lib/node_modules/Haraka/outbound/hmail.js:780:33)
[CRIT] [-] [core]     at emitOne (events.js:116:13)
[CRIT] [-] [core]     at pluggableStream.emit (events.js:211:7)
[CRIT] [-] [core]     at pluggableStream.on_socket_data (/usr/lib/node_modules/Haraka/line_socket.js:25:20)
[CRIT] [-] [core]     at emitOne (events.js:116:13)
[CRIT] [-] [core]     at pluggableStream.emit (events.js:211:7)
[CRIT] [-] [core]     at Socket.<anonymous> (/usr/lib/node_modules/Haraka/tls_socket.js:59:18)
[NOTICE] [-] [core] Shutting down
```

Checklist:
- [ ] docs updated
- [ ] tests updated
- [x] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

### CODE REVIEW

**Comment by baudehlo** [comment]
Does this also fix #2509?

**Comment by analogic** [comment]
I can't tell, protocol log is really helping here

**Comment by analogic** [comment]
This bug (actualy sending RSET) for me is triggered by email which have broken headers (there is another escaping issue yet hidden from me)

**Comment by msimerson** [comment]
Is refraining from ever sending RSET on a LMTP connection a good solution?  (If yes, I'm okay with it, but I'd love to hear a little more explanation). It feels a little like a workaround to solving whatever the underlying issue is. Maybe it's both?

**Comment by baudehlo** [comment]
Yeah there’s no RSET command in LMTP.

https://tools.ietf.org/html/rfc2033

**Comment by analogic** [comment]
@msimerson yes LMTP has no RSET. But it seems there is another bug in game which is I guess somewhat leaking email content to LMTP and triggering RSET which is normaly not issued. 

Setup haraka+lmtp (I use dovecot) and try this. Unpatched version of Haraka dies and can't be started until mail is removed from queue:
```
$ wget https://analogic.cz/mailbug
$ swaks --to valid@account.cz --from test@test.cz --data mailbug --server 172.17.0.2
```
First "problem" (it is realy not problem since headers/body are malformed) is that haraka headers are added to end of email (is parsing headers somewhat different than other smtp daemons?). Second problem is that some string in mail triggers RSET - this patch just prevent sending RSET to LMTP but there might still be some garbage hanging around.

**Comment by analogic** [comment]
Also note that delivered email is cut in a half so I suppose that some unescaped char just end LMTP session

**Comment by baudehlo** [comment]
What’s the content of mailbug?

**Comment by msimerson** [comment]
A b0rked email message:

````
$ cat /Users/matt/.Trash/mailbug.dms 
X-Mailer:Netburner Embedded Mailer
From:omgomg@test.cz
To:omgomg@test.cz
Date:Sat, 03 Nov 2018 15:42:51 +0000
Subject:Automatic mail message from ...
Owner      : ...
.
Equipment  : Micropack System
.
Location   : KTJAT - Klatovy Jatecni
.
 
.
Summary    : Battery Fuse ,Major Alarm
.
 
.
Severity   : Major Alarm
.
Event      : On 
.
 
.
Check details at http://192.168.1.254
.
 
.
Additional Info: 
.
                 
.
-------------------------------------------------------------
.
This message was sent to you by an automatic emailer service 
.
-------------------------------------------------------------
.
 
.
 
.
X-Rspamd-Bar: +++++++++++++++++++++
X-Rspamd-Report: ONCE_RECEIVED(0.1) XM_UA_NO_VERSION(0.01) HFILTER_HOSTNAME_2(1) MIME_GOOD(-0.1) HFILTER_HELO_BADIP(4.5) DMARC_POLICY_SOFTFAIL(0.1) DATE_IN_FUTURE(4) MISSING_MID(2.5) RCVD_NO_TLS_LAST(0.1) IP_SCORE(-0.450655) BROKEN_HEADERS(10)
X-Rspamd-Score: 21.759345
Message-Id: <7D92644B-FE27-4A6C-AE7E-49BBCA60F726.1>

..

````

**Pull request merged**
