### PR TITLE
Rspamd plugin: restore spam report header

### LINKED ISSUE #1563: Rspamd report header doesn't work
### Haraka version

Tested git but should affect released versions as well (probably any featuring rspamd plugin).
### Expected behavior

If headers are added (because `always_add_headers` is set or rspamd recommended `add header`)- `X-Rspamd-Report:` should contain a list of matched symbols and their scores.
### Observed behavior

`X-Rspamd-Report:` is empty.
### Explanation

Code is looking for a `score` property but nothing it sees is actually an object. Possible solutions are:
- Changing format of cleaned data to have symbols grouped in a nested object (is this bad? seems bad)
- Returning unfiltered data in addition to cleaned data used for logs etc (maybe good idea?)
- Tracking which entries are actual symbols in another object (hmmm)
### Aside (EDIT)

During the short period in which this did work, it was pretty ugly- and could likely exceed length limits- it should be wrapped. Adding symbol 'options' could be nice too . :)

### PR DESCRIPTION
**Pull request by fatalbanana**
Fixes #1563

Maybe I should just PR this. I planned to try make this header look better but I've not gotten round to that (nor other things in mind for Haraka & rspamd plugin) yet. @msimerson doesn't like having stuff nested under `default` and well, it is strange, but the idea is to really have the raw response from rspamd which makes this necessary evil. :)

Changes proposed in this pull request:
- Restore spam report header
- Round down scores for spambar
- Restore untampered rspamd JSON
- Logs should be unaffected

Checklist:
- [N/A] docs updated
- [YEBO] tests updated

### CODE REVIEW

**Comment by msimerson** [comment]
> the idea is to really have the raw response from rspamd

Right, so instead of tucking it under an ambigious name like _default_, instead choose something descriptive like `rawResult` or some such.

**Comment by fatalbanana** [comment]
Thing it's tucked under is called `data` (vs `log` which contains cleaned data). `default` is part of the response from rspamd.

**Comment by smfreegard** [comment]
It also wouldn't be called `default` if rspamd 'settings' were used e.g. per-user, per-domain etc. would it?

**Comment by fatalbanana** [comment]
My understanding is that non-default metrics are never actually used in rspamd and that `setttings` module has supplanted this functionality.

**Pull request merged**
