### PR TITLE
prevent local delivery loop when target exchange resolves to a local hostname

### LINKED ISSUE #2809: Localhost mail loop problem
I am trying to solve kind of configuration problem - it is not Haraka issue per se

There are multiple servers which returns MX as 0.0.0.0 or 127.0.0.1, or other "problematic" IPs. What happens is that Haraka will deliver to itself and relay via outbound again. It depends on added headers but after ±100 deliveries Haraka will reject mail as looped mail. 

Thing is that malicious user can easily induce dos with this kind of behaviour. Only solution I've come up is kind of hacky with abusing metadata in headers. Am I missing something?

### PR DESCRIPTION
**Pull request by DoobleD**
Fixes #2809 also for host names (#2952 solved it for IPs only). Requires merge of [haraka-net-utils#63](https://github.com/haraka/haraka-net-utils/pull/63) first.

Changes proposed in this pull request:
- new function `net_utils.is_local_host` is used instead of `net_utils.is_local_ip` to check if the exchange is localhost.

Checklist:
- [ ] docs updated
- [ ] tests updated
- [ ] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

### CODE REVIEW

**Review by msimerson — APPROVED** [review]

**Comment by DoobleD** [comment]
The call to `is_local_host` seems to badly impact performance for some reason. Applying the change to production made CPU jump from ~15% to 99%.

**Comment by msimerson** [comment]
Yes, there's a bug in it somewhere that is calling done when done is undefined. I haven't had a chance to investigate further.

**Comment by DoobleD** [comment]
> Yes, there's a bug in it somewhere that is calling done when done is undefined. I haven't had a chance to investigate further.

Thanks for the feedback @msimerson. Indeed the call to `is_local_host` in `mx_lookup.js` simply doesn't use the callback...I'll open fix PRs soon.

**Comment by DoobleD** [comment]
Here are the fix PRs:

- https://github.com/haraka/Haraka/pull/3010/
- https://github.com/haraka/haraka-net-utils/pull/65

Not sure if that works for you as it uses promises.

To be sure I tested this version on a production server and it seems to be working fine so far.

**Pull request merged**
