### PR TITLE
Add class, constructor,setupClient,setTls,set,get

### PR DESCRIPTION
**Pull request by MuraraAllan**
Add class Connection respective constructor following params, a static method for setupClient, setTls, set and get methods.

Fixes #

Changes proposed in this pull request:
-  
- 

Checklist:
- [ ] docs updated
- [ ] tests updated
- [ ] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

As the file have a lot of functions to convert and this is my first PR to this Repo, i'd prefer to open and ask for review and commit the changes as i work. (Think will turn easier to review too.)
Started working today, should finish the PR tomorrow.

### CODE REVIEW

**Comment by msimerson** [comment]
In your local repo, you can run `npm run lint` as well. Sometimes, `npm run lintfix` will also do some helpful magic. :)

**Comment by MuraraAllan** [comment]
Thank you, there is really magic. all the lint errors for space are gone with lintfix, save me some spaces.

**Comment by msimerson** [comment]
thanks @MuraraAllan

**Comment by MuraraAllan** [comment]
ooh, i'm still looking over it! actually there is just 30 % converted! i was expecting this keep open while i finish this as i commented @msimerson, i'm almost done here!

**Pull request merged**
