### PR TITLE
P42: if-else conditional streamlining

### PR DESCRIPTION
**Pull request by unquietwiki**
https://p42.ai/documentation/code-assist/convert-if-else-to-conditional-expression

### CODE REVIEW

**Comment by unquietwiki** [comment]
Note: this requires #3129 to be used.

**Comment by unquietwiki** [comment]
Trying to re-factor in the last set of changes from upstream + additional if-else work I was pursuing.

**Comment by msimerson** [comment]
FYI: you can keep doing that locally and then [force] push it to this branch, and leave the PR open.

**Comment by unquietwiki** [comment]
@msimerson Yeah, that was what I was doing before, but after those upstream changes, I had already diverged into a follow-up branch. What I'm building now is a series of related commits for the if-else logic, that depend on each other to work. I'm being very careful about the order of changes, so they'll resolve correctly.

**Pull request closed without merging**
