### PR TITLE
Add node v8

### PR DESCRIPTION
**Pull request by baudehlo**
This just adds v8 to travis.

Currently failing due to: https://github.com/nodejs/node/issues/13325

Edit: Newer bug report: https://github.com/nodejs/node/issues/13548

### CODE REVIEW

**Comment by msimerson** [comment]
I rebased this against master and now the v7 test failure is resolved.

**Comment by msimerson** [comment]
I have added node v8 to `allow_failures` so that the test suite is run but failures on v8 only don't cause the test suite to fail. That permits this PR (and subsequent) to be merged, will run the v8 tests against our code, and when the upstream issue gets fixed, we can remove v8 from the allowed_failures list.

**Comment by superman20** [comment]
What impact does this upstream bug have on Haraka?  Is it a serious issue such that you wouldn't run v8 until resolved or is it a fringe issue only encountered when using certain features?

**Comment by baudehlo** [comment]
It means Haraka won't start.

**Pull request merged**
