### PR TITLE
Get pool

### PR DESCRIPTION
**Pull request by msimerson**
Changes proposed in this pull request:
- pass cfg object instead of multiple params, simplifying get_pool calls
- whitespace/style updates
- add integration test: send/deliver message w/smtp_client

Checklist:
- [x] docs updated
- [x] tests updated

### CODE REVIEW

**Comment by baudehlo** [comment]
Urg, it's getting harder and harder to keep up to date with the
splitting... I may have to start over. At least the pressure is on.

**Comment by msimerson** [comment]
Shouldn't you be able to rebase your outbound branch against master?  (I do it so often that I've written a shell alias for it):

```sh
alias gruh='git remote update haraka && git rebase haraka/master && git push -f'
```

Of course, that only works if you have a checkout named 'haraka', but I do that for all my haraka* repos. If/when it doesn't rebase cleanly, it'll stop and you can do the merge/edits and then `git rebase --continue`.

**Comment by baudehlo** [comment]
Doesn't help when you've split a big file up. Git only understands renames not splits.

**Comment by msimerson** [comment]
> Git only understands renames

Ahhhh right, sorry. :-(

**Pull request merged**
