### PR TITLE
unfog a mystery

### PR DESCRIPTION
**Pull request by msimerson**
Pay special attention to the removed comment, and then all shall become clear.

### CODE REVIEW

**Comment by Dexus** [comment]
:+1: never use same variable in global and local scorp...

**Comment by baudehlo** [comment]
Seems like something lint could/should warn about?

**Comment by msimerson** [comment]
> Seems like something lint could/should warn about?

Sure enough, it's called shadowing and there's a [no-shadow rule](http://eslint.org/docs/rules/no-shadow). Unfortunately, there are 99 instances in our code where we've ignored that "never use same variable in global and local scope" principle. I've pushed another commit that enables that rule in warnings mode.

If we want to lint to catch those errors for us (+1 from me) then we need to clean up the rest of those cases and switch from warnings to errors.

**Comment by msimerson** [comment]
# Lint results

````
$ grunt lint
Running "eslint:main" (eslint) task

/Users/matt/Documents/git/haraka/fsync_writestream.js
  42:54  warning  'er' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/logger.js
   74:24  warning  'level' is already declared in the upper scope  no-shadow
  135:30  warning  'level' is already declared in the upper scope  no-shadow
  165:33  warning  'level' is already declared in the upper scope  no-shadow
  212:14  warning  'level' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/mailheader.js
  49:49  warning  'key' is already declared in the upper scope  no-shadow
  50:45  warning  'val' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/outbound.js
   642:31  warning  'path' is already declared in the upper scope       no-shadow
   668:35  warning  'key' is already declared in the upper scope        no-shadow
   677:47  warning  'key' is already declared in the upper scope        no-shadow
   881:38  warning  'err' is already declared in the upper scope        no-shadow
   881:43  warning  'addresses' is already declared in the upper scope  no-shadow
   976:9   warning  'host' is already declared in the upper scope       no-shadow
  1038:9   warning  'host' is already declared in the upper scope       no-shadow
  1046:64  warning  'host' is already declared in the upper scope       no-shadow
  1399:29  warning  'key' is already declared in the upper scope        no-shadow
  1404:88  warning  'cert' is already declared in the upper scope       no-shadow
  1767:62  warning  'err' is already declared in the upper scope        no-shadow
  1772:78  warning  'msg' is already declared in the upper scope        no-shadow
  1791:59  warning  'host' is already declared in the upper scope       no-shadow

/Users/matt/Documents/git/haraka/plugins.js
  247:40  warning  'key' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/server.js
  182:41  warning  'plugins' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/spf.js
  282:42  warning  'err' is already declared in the upper scope  no-shadow
  305:43  warning  'err' is already declared in the upper scope  no-shadow
  499:47  warning  'err' is already declared in the upper scope  no-shadow
  581:52  warning  'err' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/tls_socket.js
  170:45  warning  'cb' is already declared in the upper scope       no-shadow
  275:32  warning  'options' is already declared in the upper scope  no-shadow
  275:41  warning  'cb' is already declared in the upper scope       no-shadow

/Users/matt/Documents/git/haraka/plugins/attachment.js
   80:25  warning  'files' is already declared in the upper scope   no-shadow
  124:17  warning  'f' is already declared in the upper scope       no-shadow
  138:32  warning  'file' is already declared in the upper scope    no-shadow
  138:38  warning  'depth' is already declared in the upper scope   no-shadow
  139:44  warning  'err' is already declared in the upper scope     no-shadow
  144:33  warning  'cmd' is already declared in the upper scope     no-shadow
  148:89  warning  'stdout' is already declared in the upper scope  no-shadow
  148:97  warning  'stderr' is already declared in the upper scope  no-shadow
  264:84  warning  'err' is already declared in the upper scope     no-shadow

/Users/matt/Documents/git/haraka/plugins/connect.fcrdns.js
  105:61  warning  'err' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/plugins/daemonize.js
  29:47  warning  'pid' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/plugins/data.uribl.js
  214:13  warning  'lookup' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/plugins/dns_list_base.js
   73:49  warning  'err' is already declared in the upper scope  no-shadow
  171:54  warning  'err' is already declared in the upper scope  no-shadow
  171:59  warning  'a' is already declared in the upper scope    no-shadow

/Users/matt/Documents/git/haraka/plugins/graph.js
  81:30  warning  'err' is already declared in the upper scope  no-shadow
  99:30  warning  'err' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/plugins/greylist.js
  221:100  warning  'err' is already declared in the upper scope     no-shadow
  292:59   warning  'err' is already declared in the upper scope     no-shadow
  578:61   warning  'err' is already declared in the upper scope     no-shadow
  578:66   warning  'result' is already declared in the upper scope  no-shadow
  599:38   warning  'record' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/plugins/helo.checks.js
  535:22  warning  'e' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/plugins/karma.js
  491:29  warning  'err' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/plugins/lookup_rdns.strict.js
  137:35  warning  'rdns' is already declared in the upper scope  no-shadow
  138:55  warning  'err' is already declared in the upper scope   no-shadow
  149:26  warning  'i' is already declared in the upper scope     no-shadow

/Users/matt/Documents/git/haraka/plugins/mail_from.is_resolvable.js
  96:63  warning  'err' is already declared in the upper scope        no-shadow
  96:68  warning  'addresses' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/plugins/queue/qmail-queue.js
  75:22  warning  'i' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/plugins/queue/rabbitmq_amqplib.js
  41:45  warning  'err' is already declared in the upper scope  no-shadow
  43:88  warning  'err' is already declared in the upper scope  no-shadow
  47:31  warning  'err' is already declared in the upper scope  no-shadow
  47:36  warning  'ok' is already declared in the upper scope   no-shadow

/Users/matt/Documents/git/haraka/plugins/rate_limit.js
  163:37   warning  'err' is already declared in the upper scope    no-shadow
  263:74   warning  'err' is already declared in the upper scope    no-shadow
  278:114  warning  'err' is already declared in the upper scope    no-shadow
  278:119  warning  'key' is already declared in the upper scope    no-shadow
  278:124  warning  'value' is already declared in the upper scope  no-shadow
  282:71   warning  'err' is already declared in the upper scope    no-shadow
  358:90   warning  'err' is already declared in the upper scope    no-shadow

/Users/matt/Documents/git/haraka/plugins/rcpt_to.ldap.js
  86:34  warning  'err' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/plugins/reseed_rng.js
  194:17  warning  'i' is already declared in the upper scope  no-shadow
  194:44  warning  't' is already declared in the upper scope  no-shadow
  195:17  warning  'j' is already declared in the upper scope  no-shadow
  195:44  warning  'u' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/plugins/spf.js
  162:13  warning  'auth_result' is already declared in the upper scope  no-shadow

/Users/matt/Documents/git/haraka/plugins/watch/html/jquery.tipsy.js
  202:17  warning  'tipsy' is already declared in the upper scope  no-shadow
  214:17  warning  'tipsy' is already declared in the upper scope  no-shadow
  230:17  warning  'tipsy' is already declared in the upper scope  no-shadow

✖ 79 problems (0 errors, 79 warnings)


Running "eslint:test" (eslint) task

/Users/matt/Documents/git/haraka/tests/plugins/rcpt_to.routes.js
  65:39  warning  'err' is already declared in the upper scope  no-shadow

✖ 1 problem (0 errors, 1 warning)


Done, without errors.
````

**Comment by baudehlo** [comment]
I'm fine with it even in warnings mode - it would be helpful to just see it.

**Comment by msimerson** [comment]
> it would be helpful to just see it

Problem is, until we get the pile of warnings cleaned up, nobody will ever notice that one more showed up in the big long list. I'll work on that later.

**Comment by baudehlo** [comment]
Well the annoying thing is, because of the way JS works, won't it show for
things like:

for (var i=0;...) {
}
for (var i=0;...) {
}

?

And for:

some_async(function (err) {
    other_async(function (err) {
    })
});

?

**Comment by msimerson** [comment]
Yup. Hence, the use of `for (var i=0...)` and `for (var j=0;....)`, and similar workarounds, to prevent inadvertent variable hoisting, shadowing, and accidentally overloading variables with named functions.

**Comment by baudehlo** [comment]
I guess once we can mandate node 4 we can just use "let" :)

**Comment by msimerson** [comment]
Good point, and yet another reason to cease supporting 0.__  :-)

**Comment by msimerson** [comment]
Branch updated, all shadow variable usage has been exorcised and the lint checks will raise an alarm to prevent future transgressions.

**Pull request merged**
