### PR TITLE
Changed get_denyfn Function to ES6

### PR DESCRIPTION
**Pull request by codealtgeek**
Fixes #

Changes proposed in this pull request:
- 
- 

Checklist:
- [ ] docs updated
- [ ] tests updated
- [ ] [Changes](https://github.com/haraka/Haraka/blob/master/Changes.md) updated

### CODE REVIEW

**Comment by msimerson** [comment]
Next step: get the CI tests to pass.

**Comment by codealtgeek** [comment]
How do I run the test?? I am a student and new.. sorry I am trying to learn
what to do so if you explain it I will definitely do it.. These are the
only ones I can even remotely do for hacktoberfest..

**Comment by msimerson** [comment]
The tests run automatically. Every time out add a commit and push it to GitHub. Follow the "Details" links next to the Travis CI build.

**Comment by baudehlo** [comment]
Or you can run them before push with:

$ npm test

Also run the linting with:

$ npm run lint

**Comment by codealtgeek** [comment]
Ahhh so npm test works with other stuff as well. I am in a boot camp and we
use npm test for our tests but I am in the beginning weeks so I was not
sure it was a widely huge thing lol still learning..

**Comment by msimerson** [comment]
> Ahhh so npm test works with other stuff as well.

Yep, it's an ecosystem convention. When in doubt, just try it, and it'll probably work. :)

**Comment by msimerson** [comment]
completed in #2239

**Pull request closed without merging**
